import { z } from 'zod';

import { salarySchema } from '@/schema/salarySchma.schema';
import { EmployeeType } from './employeeType';

export type SalaryType = z.infer<typeof salarySchema>;

export interface CategoryTableType {
  id: number;
  employee_id: number;
  salary_day: number;
  salary_night: number;
  probationary_salary_basic_26days: number;
  probationary_salary_basic_hours: number;
  probationary_salary_basic_extra_hours: number;
  allowance_apprentice: number;
  salary_basic: number;
  regular_salary_hour: number;
  salary_overtime: number;
  allowance_diligence: number;
  allowance_responsibility: number;
  allowance_overtime: number;
  allowance_night: number;
  allowance_rice: number;
  company_insurance: number;
  insurance: number;
  employee: EmployeeType;
}

export interface SalaryTableType {
  id: number;
  employee_id: number;
  salary_total: number;
  insurance_payroll: number;
  advance_money_payroll: number;
  company_insurance_payroll: number;
  KPI_Subtraction_payroll: number;
  previous_period_debt_payroll: number;
  actually_received_payroll: number;
  employee: EmployeeType;
}

export interface SalaryDetailTableType {
  id: number;
  employee_id: number;
  number_of_work_days_trial: number;
  day_shift_salary_trial: number;
  day_shift_salary_trial_notice: string;
  number_of_work_nights_trial: number;
  night_shift_salary_trial: number;
  night_shift_salary_trial_notice: string;
  overtime_hours_trial: number;
  overtime_salary_trial: number;
  overtime_salary_trial_notice: string;
  number_of_work: number;
  allowance_apprentice_detail: number;
  allowance_apprentice_detail_notice: string;
  core_hours: number;
  official_salary: number;
  official_salary_notice: string;
  number_of_hours_worked: number;
  allowance_diligence_detail: number;
  allowance_diligence_detail_notice: string;
  allowance_professional_detail?: number;
  allowance_professional_detail_notice?: string;
  number_of_jobs: number;
  allowance_responsibility_detail: number;
  allowance_responsibility_detail_notice: string;
  overtime_hours_detail: number;
  overtime_salary: number;
  overtime_salary_notice: string;
  reinforcement_hours_detail?: number;
  reinforcement_salary?: number;
  reinforcement_salary_notice?: string;
  number_of_work_days: number;
  allowance_rice_detail: number;
  allowance_rice_detail_notice: string;
  number_of_work_nights: number;
  allowance_shift_night: number;
  allowance_shift_night_notice: string;
  overtime_day_count_detail: number;
  allowance_overtime_detail: number;
  allowance_overtime_detail_notice: string;
  holidays_count_detail: number;
  holidays_money: number;
  holidays_money_notice: string;
  paid_holidays_count_detail: number;
  paid_holidays_money: number;
  paid_holidays_money_notice: string;
  business_travel_hours: number;
  business_travel_unit_price_hour: number;
  gcn_business_travel_salary: number;
  gcn_business_travel_salary_notice: string;
  number_of_business_trips: number;
  business_fuel_unit_price_day: number;
  allowance_gcn_business_fuel: number;
  allowance_gcn_business_fuel_notice: string;
  money_referral_people: number;
  money_referral_people_notice: string;
  allowance_diffrent: number;
  allowance_diffrent_notice: string;
  bonuses_for_attendance: number;
  bonuses_for_attendance_notice: string;
  previous_month_kpi_refund?: number;
  previous_month_kpi_refund_notice?: string;
  sickness: number;
  sickness_notice: string;
  funeral: number;
  funeral_notice: string;
  birthday_money: number;
  birthday_money_notice: string;
  previous_period_debt: number;
  previous_period_debt_notice: string;
  total_income: number;
  insurance_detail: number;
  insurance_detail_notice: string;
  advance_money: number;
  advance_money_notice: string;
  number_of_violations: number;
  union_fee?: number;
  union_fee_notice?: string;
  subtract_of_violations?: number;
  subtract_of_violations_notice?: string;
  unicon_deduction?: number;
  unicon_deduction_notice?: string;
  daysleave_allowed: number;
  subtract_daysleave_allowed: number;
  subtract_daysleave_allowed_notice: string;
  daysleave_notallowed: number;
  subtract_daysleave_notallowed: number;
  subtract_daysleave_notallowed_notice: string;
  error_serious: number;
  subtract_error_serious: number;
  subtract_error_serious_notice: string;
  error_minor: number;
  subtract_error_minor: number;
  subtract_error_minor_notice: string;
  kpi_subtraction: number;
  kpi_subtraction_notice: string;
  actually_received: number;
  forms_of_payment: string;
  company_insurance_detail: number;
  employee: EmployeeType;
  salary_manager: SalaryType;
}
export interface AttendanceTableType {
  id: number;
  employee_id: number;
  total_day_offical: number;
  total_night_offical: number;
  total_overtime_offical: number;
  workday_count_trial: number;
  worknight_count_trial: number;
  overtime_day_count_trial: number;
  allowance_rice_day_timekeeping: number;
  allowance_rice_night_timekeeping: number;
  allowance_overtime_timekeeping: number;
  holidays_count: number;
  paid_holidays_count: number;
  daysleave_allowed_timekeeping: number;
  daysleave_notallowed_timekeeping: number;
  employee: EmployeeType;
  salary_official_v_v_p_timekeepings?: {
    id: number;
    salary_official_vvp_id: number;
    timekeeping_date: string;
    timekeeping_day: number;
    timekeeping_night: number;
    timekeeping_overtime: number;
  }[];
  salary_official_a7_a_timekeepings?: {
    id: number;
    salary_official_a7a_id: number;
    timekeeping_date: string;
    timekeeping_day: number;
    timekeeping_night: number;
    timekeeping_overtime: number;
  }[];
  times: {
    id: number;
    timekeeping_date: string;
    timekeeping_day: number;
    timekeeping_night: number;
    timekeeping_overtime: number;
  }[];
}
