/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ForbiddenImport } from './routes/forbidden'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as authRouteImport } from './routes/(auth)/route'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as authLoginImport } from './routes/(auth)/login'
import { Route as AuthenticatedEmployeeRouteImport } from './routes/_authenticated/employee/route'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedEmployeeIndexImport } from './routes/_authenticated/employee/index'
import { Route as AuthenticatedAdminIndexImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminActivityScheduleImport } from './routes/_authenticated/admin/activity-schedule'
import { Route as AuthenticatedAdminActivityHistoryImport } from './routes/_authenticated/admin/activity-history'
import { Route as AuthenticatedAdminAboutImport } from './routes/_authenticated/admin/about'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin/products/route'
import { Route as AuthenticatedEmployeeSchedulesIndexImport } from './routes/_authenticated/employee/schedules/index'
import { Route as AuthenticatedEmployeeSalariesIndexImport } from './routes/_authenticated/employee/salaries/index'
import { Route as AuthenticatedEmployeeActivityScheduleIndexImport } from './routes/_authenticated/employee/activity-schedule/index'
import { Route as AuthenticatedAdminWorkSchedulesIndexImport } from './routes/_authenticated/admin/work-schedules/index'
import { Route as AuthenticatedAdminWorkScheduleCategoriesIndexImport } from './routes/_authenticated/admin/work-schedule-categories/index'
import { Route as AuthenticatedAdminSalariesIndexImport } from './routes/_authenticated/admin/salaries/index'
import { Route as AuthenticatedAdminRolesIndexImport } from './routes/_authenticated/admin/roles/index'
import { Route as AuthenticatedAdminProductsIndexImport } from './routes/_authenticated/admin/products/index'
import { Route as AuthenticatedAdminEmployeesIndexImport } from './routes/_authenticated/admin/employees/index'
import { Route as AuthenticatedAdminCheckPoIndexImport } from './routes/_authenticated/admin/check-po/index'
import { Route as AuthenticatedEmployeeTodoUpdateQuantityErrorImport } from './routes/_authenticated/employee/todo/update-quantity-error'
import { Route as AuthenticatedEmployeeTodoUpdateQuantityImport } from './routes/_authenticated/employee/todo/update-quantity'
import { Route as AuthenticatedEmployeeTodoHistoryImport } from './routes/_authenticated/employee/todo/history'
import { Route as AuthenticatedEmployeeTodoAddProductImport } from './routes/_authenticated/employee/todo/add-product'
import { Route as AuthenticatedEmployeeStampsRequestImport } from './routes/_authenticated/employee/stamps/request'
import { Route as AuthenticatedEmployeeSchedulesIdImport } from './routes/_authenticated/employee/schedules/$id'
import { Route as AuthenticatedEmployeeSalariesIdImport } from './routes/_authenticated/employee/salaries/$id'
import { Route as AuthenticatedAdminWorkSchedulesIdImport } from './routes/_authenticated/admin/work-schedules/$id'
import { Route as AuthenticatedAdminStampsRequestImport } from './routes/_authenticated/admin/stamps/request'
import { Route as AuthenticatedAdminStampsHistoryImport } from './routes/_authenticated/admin/stamps/history'
import { Route as AuthenticatedAdminStampsBoxImport } from './routes/_authenticated/admin/stamps/box'
import { Route as AuthenticatedAdminStampsBagImport } from './routes/_authenticated/admin/stamps/bag'
import { Route as AuthenticatedAdminProductsTrashImport } from './routes/_authenticated/admin/products/trash'
import { Route as AuthenticatedAdminProductsAddImport } from './routes/_authenticated/admin/products/add'
import { Route as AuthenticatedAdminPlansProductionImport } from './routes/_authenticated/admin/plans/production'
import { Route as AuthenticatedAdminPlansMaterialImport } from './routes/_authenticated/admin/plans/material'
import { Route as AuthenticatedAdminEmployeesAddImport } from './routes/_authenticated/admin/employees/add'
import { Route as AuthenticatedAdminAttendancesRecordImport } from './routes/_authenticated/admin/attendances/record'
import { Route as AuthenticatedAdminAttendancesHistoryImport } from './routes/_authenticated/admin/attendances/history'
import { Route as AuthenticatedEmployeeAttendancesHistoryIndexImport } from './routes/_authenticated/employee/attendances/history/index'
import { Route as AuthenticatedEmployeeAttendancesCalculateIndexImport } from './routes/_authenticated/employee/attendances/calculate/index'
import { Route as AuthenticatedAdminEmployeesTrashIndexImport } from './routes/_authenticated/admin/employees/trash/index'
import { Route as AuthenticatedAdminProductsQuantityUpdateImport } from './routes/_authenticated/admin/products/quantity/update'
import { Route as AuthenticatedAdminProductsQuantityAddImport } from './routes/_authenticated/admin/products/quantity/add'
import { Route as AuthenticatedAdminProductsEditIdImport } from './routes/_authenticated/admin/products/edit.$id'
import { Route as AuthenticatedAdminEmployeesEditIdImport } from './routes/_authenticated/admin/employees/edit.$id'

// Create Virtual Routes

const AuthenticatedAdminSalariesIdLazyImport = createFileRoute(
  '/_authenticated/admin/salaries/$id',
)()

// Create/Update Routes

const ForbiddenRoute = ForbiddenImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const authRouteRoute = authRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const authLoginRoute = authLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)

const AuthenticatedEmployeeRouteRoute = AuthenticatedEmployeeRouteImport.update(
  {
    id: '/employee',
    path: '/employee',
    getParentRoute: () => AuthenticatedRoute,
  } as any,
)

const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedEmployeeIndexRoute = AuthenticatedEmployeeIndexImport.update(
  {
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEmployeeRouteRoute,
  } as any,
)

const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)

const AuthenticatedAdminActivityScheduleRoute =
  AuthenticatedAdminActivityScheduleImport.update({
    id: '/activity-schedule',
    path: '/activity-schedule',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

const AuthenticatedAdminActivityHistoryRoute =
  AuthenticatedAdminActivityHistoryImport.update({
    id: '/activity-history',
    path: '/activity-history',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

const AuthenticatedAdminAboutRoute = AuthenticatedAdminAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)

const AuthenticatedAdminProductsRouteRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

const AuthenticatedEmployeeSchedulesIndexRoute =
  AuthenticatedEmployeeSchedulesIndexImport.update({
    id: '/schedules/',
    path: '/schedules/',
    getParentRoute: () => AuthenticatedEmployeeRouteRoute,
  } as any)

const AuthenticatedEmployeeSalariesIndexRoute =
  AuthenticatedEmployeeSalariesIndexImport.update({
    id: '/salaries/',
    path: '/salaries/',
    getParentRoute: () => AuthenticatedEmployeeRouteRoute,
  } as any)

const AuthenticatedEmployeeActivityScheduleIndexRoute =
  AuthenticatedEmployeeActivityScheduleIndexImport.update({
    id: '/activity-schedule/',
    path: '/activity-schedule/',
    getParentRoute: () => AuthenticatedEmployeeRouteRoute,
  } as any)

const AuthenticatedAdminWorkSchedulesIndexRoute =
  AuthenticatedAdminWorkSchedulesIndexImport.update({
    id: '/work-schedules/',
    path: '/work-schedules/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

const AuthenticatedAdminWorkScheduleCategoriesIndexRoute =
  AuthenticatedAdminWorkScheduleCategoriesIndexImport.update({
    id: '/work-schedule-categories/',
    path: '/work-schedule-categories/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

const AuthenticatedAdminSalariesIndexRoute =
  AuthenticatedAdminSalariesIndexImport.update({
    id: '/salaries/',
    path: '/salaries/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

const AuthenticatedAdminRolesIndexRoute =
  AuthenticatedAdminRolesIndexImport.update({
    id: '/roles/',
    path: '/roles/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

const AuthenticatedAdminProductsIndexRoute =
  AuthenticatedAdminProductsIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminProductsRouteRoute,
  } as any)

const AuthenticatedAdminEmployeesIndexRoute =
  AuthenticatedAdminEmployeesIndexImport.update({
    id: '/employees/',
    path: '/employees/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

const AuthenticatedAdminCheckPoIndexRoute =
  AuthenticatedAdminCheckPoIndexImport.update({
    id: '/check-po/',
    path: '/check-po/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

const AuthenticatedAdminSalariesIdLazyRoute =
  AuthenticatedAdminSalariesIdLazyImport.update({
    id: '/salaries/$id',
    path: '/salaries/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/admin/salaries/$id.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedEmployeeTodoUpdateQuantityErrorRoute =
  AuthenticatedEmployeeTodoUpdateQuantityErrorImport.update({
    id: '/todo/update-quantity-error',
    path: '/todo/update-quantity-error',
    getParentRoute: () => AuthenticatedEmployeeRouteRoute,
  } as any)

const AuthenticatedEmployeeTodoUpdateQuantityRoute =
  AuthenticatedEmployeeTodoUpdateQuantityImport.update({
    id: '/todo/update-quantity',
    path: '/todo/update-quantity',
    getParentRoute: () => AuthenticatedEmployeeRouteRoute,
  } as any)

const AuthenticatedEmployeeTodoHistoryRoute =
  AuthenticatedEmployeeTodoHistoryImport.update({
    id: '/todo/history',
    path: '/todo/history',
    getParentRoute: () => AuthenticatedEmployeeRouteRoute,
  } as any)

const AuthenticatedEmployeeTodoAddProductRoute =
  AuthenticatedEmployeeTodoAddProductImport.update({
    id: '/todo/add-product',
    path: '/todo/add-product',
    getParentRoute: () => AuthenticatedEmployeeRouteRoute,
  } as any)

const AuthenticatedEmployeeStampsRequestRoute =
  AuthenticatedEmployeeStampsRequestImport.update({
    id: '/stamps/request',
    path: '/stamps/request',
    getParentRoute: () => AuthenticatedEmployeeRouteRoute,
  } as any)

const AuthenticatedEmployeeSchedulesIdRoute =
  AuthenticatedEmployeeSchedulesIdImport.update({
    id: '/schedules/$id',
    path: '/schedules/$id',
    getParentRoute: () => AuthenticatedEmployeeRouteRoute,
  } as any)

const AuthenticatedEmployeeSalariesIdRoute =
  AuthenticatedEmployeeSalariesIdImport.update({
    id: '/salaries/$id',
    path: '/salaries/$id',
    getParentRoute: () => AuthenticatedEmployeeRouteRoute,
  } as any)

const AuthenticatedAdminWorkSchedulesIdRoute =
  AuthenticatedAdminWorkSchedulesIdImport.update({
    id: '/work-schedules/$id',
    path: '/work-schedules/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

const AuthenticatedAdminStampsRequestRoute =
  AuthenticatedAdminStampsRequestImport.update({
    id: '/stamps/request',
    path: '/stamps/request',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

const AuthenticatedAdminStampsHistoryRoute =
  AuthenticatedAdminStampsHistoryImport.update({
    id: '/stamps/history',
    path: '/stamps/history',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

const AuthenticatedAdminStampsBoxRoute =
  AuthenticatedAdminStampsBoxImport.update({
    id: '/stamps/box',
    path: '/stamps/box',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

const AuthenticatedAdminStampsBagRoute =
  AuthenticatedAdminStampsBagImport.update({
    id: '/stamps/bag',
    path: '/stamps/bag',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

const AuthenticatedAdminProductsTrashRoute =
  AuthenticatedAdminProductsTrashImport.update({
    id: '/trash',
    path: '/trash',
    getParentRoute: () => AuthenticatedAdminProductsRouteRoute,
  } as any)

const AuthenticatedAdminProductsAddRoute =
  AuthenticatedAdminProductsAddImport.update({
    id: '/add',
    path: '/add',
    getParentRoute: () => AuthenticatedAdminProductsRouteRoute,
  } as any)

const AuthenticatedAdminPlansProductionRoute =
  AuthenticatedAdminPlansProductionImport.update({
    id: '/plans/production',
    path: '/plans/production',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

const AuthenticatedAdminPlansMaterialRoute =
  AuthenticatedAdminPlansMaterialImport.update({
    id: '/plans/material',
    path: '/plans/material',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

const AuthenticatedAdminEmployeesAddRoute =
  AuthenticatedAdminEmployeesAddImport.update({
    id: '/employees/add',
    path: '/employees/add',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

const AuthenticatedAdminAttendancesRecordRoute =
  AuthenticatedAdminAttendancesRecordImport.update({
    id: '/attendances/record',
    path: '/attendances/record',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

const AuthenticatedAdminAttendancesHistoryRoute =
  AuthenticatedAdminAttendancesHistoryImport.update({
    id: '/attendances/history',
    path: '/attendances/history',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

const AuthenticatedEmployeeAttendancesHistoryIndexRoute =
  AuthenticatedEmployeeAttendancesHistoryIndexImport.update({
    id: '/attendances/history/',
    path: '/attendances/history/',
    getParentRoute: () => AuthenticatedEmployeeRouteRoute,
  } as any)

const AuthenticatedEmployeeAttendancesCalculateIndexRoute =
  AuthenticatedEmployeeAttendancesCalculateIndexImport.update({
    id: '/attendances/calculate/',
    path: '/attendances/calculate/',
    getParentRoute: () => AuthenticatedEmployeeRouteRoute,
  } as any)

const AuthenticatedAdminEmployeesTrashIndexRoute =
  AuthenticatedAdminEmployeesTrashIndexImport.update({
    id: '/employees/trash/',
    path: '/employees/trash/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

const AuthenticatedAdminProductsQuantityUpdateRoute =
  AuthenticatedAdminProductsQuantityUpdateImport.update({
    id: '/quantity/update',
    path: '/quantity/update',
    getParentRoute: () => AuthenticatedAdminProductsRouteRoute,
  } as any)

const AuthenticatedAdminProductsQuantityAddRoute =
  AuthenticatedAdminProductsQuantityAddImport.update({
    id: '/quantity/add',
    path: '/quantity/add',
    getParentRoute: () => AuthenticatedAdminProductsRouteRoute,
  } as any)

const AuthenticatedAdminProductsEditIdRoute =
  AuthenticatedAdminProductsEditIdImport.update({
    id: '/edit/$id',
    path: '/edit/$id',
    getParentRoute: () => AuthenticatedAdminProductsRouteRoute,
  } as any)

const AuthenticatedAdminEmployeesEditIdRoute =
  AuthenticatedAdminEmployeesEditIdImport.update({
    id: '/employees/edit/$id',
    path: '/employees/edit/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authRouteImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/employee': {
      id: '/_authenticated/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof AuthenticatedEmployeeRouteImport
      parentRoute: typeof AuthenticatedImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginImport
      parentRoute: typeof authRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/admin/about': {
      id: '/_authenticated/admin/about'
      path: '/about'
      fullPath: '/admin/about'
      preLoaderRoute: typeof AuthenticatedAdminAboutImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/admin/activity-history': {
      id: '/_authenticated/admin/activity-history'
      path: '/activity-history'
      fullPath: '/admin/activity-history'
      preLoaderRoute: typeof AuthenticatedAdminActivityHistoryImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/admin/activity-schedule': {
      id: '/_authenticated/admin/activity-schedule'
      path: '/activity-schedule'
      fullPath: '/admin/activity-schedule'
      preLoaderRoute: typeof AuthenticatedAdminActivityScheduleImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/employee/': {
      id: '/_authenticated/employee/'
      path: '/'
      fullPath: '/employee/'
      preLoaderRoute: typeof AuthenticatedEmployeeIndexImport
      parentRoute: typeof AuthenticatedEmployeeRouteImport
    }
    '/_authenticated/admin/attendances/history': {
      id: '/_authenticated/admin/attendances/history'
      path: '/attendances/history'
      fullPath: '/admin/attendances/history'
      preLoaderRoute: typeof AuthenticatedAdminAttendancesHistoryImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/admin/attendances/record': {
      id: '/_authenticated/admin/attendances/record'
      path: '/attendances/record'
      fullPath: '/admin/attendances/record'
      preLoaderRoute: typeof AuthenticatedAdminAttendancesRecordImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/admin/employees/add': {
      id: '/_authenticated/admin/employees/add'
      path: '/employees/add'
      fullPath: '/admin/employees/add'
      preLoaderRoute: typeof AuthenticatedAdminEmployeesAddImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/admin/plans/material': {
      id: '/_authenticated/admin/plans/material'
      path: '/plans/material'
      fullPath: '/admin/plans/material'
      preLoaderRoute: typeof AuthenticatedAdminPlansMaterialImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/admin/plans/production': {
      id: '/_authenticated/admin/plans/production'
      path: '/plans/production'
      fullPath: '/admin/plans/production'
      preLoaderRoute: typeof AuthenticatedAdminPlansProductionImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/admin/products/add': {
      id: '/_authenticated/admin/products/add'
      path: '/add'
      fullPath: '/admin/products/add'
      preLoaderRoute: typeof AuthenticatedAdminProductsAddImport
      parentRoute: typeof AuthenticatedAdminProductsRouteImport
    }
    '/_authenticated/admin/products/trash': {
      id: '/_authenticated/admin/products/trash'
      path: '/trash'
      fullPath: '/admin/products/trash'
      preLoaderRoute: typeof AuthenticatedAdminProductsTrashImport
      parentRoute: typeof AuthenticatedAdminProductsRouteImport
    }
    '/_authenticated/admin/stamps/bag': {
      id: '/_authenticated/admin/stamps/bag'
      path: '/stamps/bag'
      fullPath: '/admin/stamps/bag'
      preLoaderRoute: typeof AuthenticatedAdminStampsBagImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/admin/stamps/box': {
      id: '/_authenticated/admin/stamps/box'
      path: '/stamps/box'
      fullPath: '/admin/stamps/box'
      preLoaderRoute: typeof AuthenticatedAdminStampsBoxImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/admin/stamps/history': {
      id: '/_authenticated/admin/stamps/history'
      path: '/stamps/history'
      fullPath: '/admin/stamps/history'
      preLoaderRoute: typeof AuthenticatedAdminStampsHistoryImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/admin/stamps/request': {
      id: '/_authenticated/admin/stamps/request'
      path: '/stamps/request'
      fullPath: '/admin/stamps/request'
      preLoaderRoute: typeof AuthenticatedAdminStampsRequestImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/admin/work-schedules/$id': {
      id: '/_authenticated/admin/work-schedules/$id'
      path: '/work-schedules/$id'
      fullPath: '/admin/work-schedules/$id'
      preLoaderRoute: typeof AuthenticatedAdminWorkSchedulesIdImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/employee/salaries/$id': {
      id: '/_authenticated/employee/salaries/$id'
      path: '/salaries/$id'
      fullPath: '/employee/salaries/$id'
      preLoaderRoute: typeof AuthenticatedEmployeeSalariesIdImport
      parentRoute: typeof AuthenticatedEmployeeRouteImport
    }
    '/_authenticated/employee/schedules/$id': {
      id: '/_authenticated/employee/schedules/$id'
      path: '/schedules/$id'
      fullPath: '/employee/schedules/$id'
      preLoaderRoute: typeof AuthenticatedEmployeeSchedulesIdImport
      parentRoute: typeof AuthenticatedEmployeeRouteImport
    }
    '/_authenticated/employee/stamps/request': {
      id: '/_authenticated/employee/stamps/request'
      path: '/stamps/request'
      fullPath: '/employee/stamps/request'
      preLoaderRoute: typeof AuthenticatedEmployeeStampsRequestImport
      parentRoute: typeof AuthenticatedEmployeeRouteImport
    }
    '/_authenticated/employee/todo/add-product': {
      id: '/_authenticated/employee/todo/add-product'
      path: '/todo/add-product'
      fullPath: '/employee/todo/add-product'
      preLoaderRoute: typeof AuthenticatedEmployeeTodoAddProductImport
      parentRoute: typeof AuthenticatedEmployeeRouteImport
    }
    '/_authenticated/employee/todo/history': {
      id: '/_authenticated/employee/todo/history'
      path: '/todo/history'
      fullPath: '/employee/todo/history'
      preLoaderRoute: typeof AuthenticatedEmployeeTodoHistoryImport
      parentRoute: typeof AuthenticatedEmployeeRouteImport
    }
    '/_authenticated/employee/todo/update-quantity': {
      id: '/_authenticated/employee/todo/update-quantity'
      path: '/todo/update-quantity'
      fullPath: '/employee/todo/update-quantity'
      preLoaderRoute: typeof AuthenticatedEmployeeTodoUpdateQuantityImport
      parentRoute: typeof AuthenticatedEmployeeRouteImport
    }
    '/_authenticated/employee/todo/update-quantity-error': {
      id: '/_authenticated/employee/todo/update-quantity-error'
      path: '/todo/update-quantity-error'
      fullPath: '/employee/todo/update-quantity-error'
      preLoaderRoute: typeof AuthenticatedEmployeeTodoUpdateQuantityErrorImport
      parentRoute: typeof AuthenticatedEmployeeRouteImport
    }
    '/_authenticated/admin/salaries/$id': {
      id: '/_authenticated/admin/salaries/$id'
      path: '/salaries/$id'
      fullPath: '/admin/salaries/$id'
      preLoaderRoute: typeof AuthenticatedAdminSalariesIdLazyImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/admin/check-po/': {
      id: '/_authenticated/admin/check-po/'
      path: '/check-po'
      fullPath: '/admin/check-po'
      preLoaderRoute: typeof AuthenticatedAdminCheckPoIndexImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/admin/employees/': {
      id: '/_authenticated/admin/employees/'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AuthenticatedAdminEmployeesIndexImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/admin/products/': {
      id: '/_authenticated/admin/products/'
      path: '/'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AuthenticatedAdminProductsIndexImport
      parentRoute: typeof AuthenticatedAdminProductsRouteImport
    }
    '/_authenticated/admin/roles/': {
      id: '/_authenticated/admin/roles/'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesIndexImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/admin/salaries/': {
      id: '/_authenticated/admin/salaries/'
      path: '/salaries'
      fullPath: '/admin/salaries'
      preLoaderRoute: typeof AuthenticatedAdminSalariesIndexImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/admin/work-schedule-categories/': {
      id: '/_authenticated/admin/work-schedule-categories/'
      path: '/work-schedule-categories'
      fullPath: '/admin/work-schedule-categories'
      preLoaderRoute: typeof AuthenticatedAdminWorkScheduleCategoriesIndexImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/admin/work-schedules/': {
      id: '/_authenticated/admin/work-schedules/'
      path: '/work-schedules'
      fullPath: '/admin/work-schedules'
      preLoaderRoute: typeof AuthenticatedAdminWorkSchedulesIndexImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/employee/activity-schedule/': {
      id: '/_authenticated/employee/activity-schedule/'
      path: '/activity-schedule'
      fullPath: '/employee/activity-schedule'
      preLoaderRoute: typeof AuthenticatedEmployeeActivityScheduleIndexImport
      parentRoute: typeof AuthenticatedEmployeeRouteImport
    }
    '/_authenticated/employee/salaries/': {
      id: '/_authenticated/employee/salaries/'
      path: '/salaries'
      fullPath: '/employee/salaries'
      preLoaderRoute: typeof AuthenticatedEmployeeSalariesIndexImport
      parentRoute: typeof AuthenticatedEmployeeRouteImport
    }
    '/_authenticated/employee/schedules/': {
      id: '/_authenticated/employee/schedules/'
      path: '/schedules'
      fullPath: '/employee/schedules'
      preLoaderRoute: typeof AuthenticatedEmployeeSchedulesIndexImport
      parentRoute: typeof AuthenticatedEmployeeRouteImport
    }
    '/_authenticated/admin/employees/edit/$id': {
      id: '/_authenticated/admin/employees/edit/$id'
      path: '/employees/edit/$id'
      fullPath: '/admin/employees/edit/$id'
      preLoaderRoute: typeof AuthenticatedAdminEmployeesEditIdImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/admin/products/edit/$id': {
      id: '/_authenticated/admin/products/edit/$id'
      path: '/edit/$id'
      fullPath: '/admin/products/edit/$id'
      preLoaderRoute: typeof AuthenticatedAdminProductsEditIdImport
      parentRoute: typeof AuthenticatedAdminProductsRouteImport
    }
    '/_authenticated/admin/products/quantity/add': {
      id: '/_authenticated/admin/products/quantity/add'
      path: '/quantity/add'
      fullPath: '/admin/products/quantity/add'
      preLoaderRoute: typeof AuthenticatedAdminProductsQuantityAddImport
      parentRoute: typeof AuthenticatedAdminProductsRouteImport
    }
    '/_authenticated/admin/products/quantity/update': {
      id: '/_authenticated/admin/products/quantity/update'
      path: '/quantity/update'
      fullPath: '/admin/products/quantity/update'
      preLoaderRoute: typeof AuthenticatedAdminProductsQuantityUpdateImport
      parentRoute: typeof AuthenticatedAdminProductsRouteImport
    }
    '/_authenticated/admin/employees/trash/': {
      id: '/_authenticated/admin/employees/trash/'
      path: '/employees/trash'
      fullPath: '/admin/employees/trash'
      preLoaderRoute: typeof AuthenticatedAdminEmployeesTrashIndexImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/employee/attendances/calculate/': {
      id: '/_authenticated/employee/attendances/calculate/'
      path: '/attendances/calculate'
      fullPath: '/employee/attendances/calculate'
      preLoaderRoute: typeof AuthenticatedEmployeeAttendancesCalculateIndexImport
      parentRoute: typeof AuthenticatedEmployeeRouteImport
    }
    '/_authenticated/employee/attendances/history/': {
      id: '/_authenticated/employee/attendances/history/'
      path: '/attendances/history'
      fullPath: '/employee/attendances/history'
      preLoaderRoute: typeof AuthenticatedEmployeeAttendancesHistoryIndexImport
      parentRoute: typeof AuthenticatedEmployeeRouteImport
    }
  }
}

// Create and export the route tree

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface AuthenticatedAdminProductsRouteRouteChildren {
  AuthenticatedAdminProductsAddRoute: typeof AuthenticatedAdminProductsAddRoute
  AuthenticatedAdminProductsTrashRoute: typeof AuthenticatedAdminProductsTrashRoute
  AuthenticatedAdminProductsIndexRoute: typeof AuthenticatedAdminProductsIndexRoute
  AuthenticatedAdminProductsEditIdRoute: typeof AuthenticatedAdminProductsEditIdRoute
  AuthenticatedAdminProductsQuantityAddRoute: typeof AuthenticatedAdminProductsQuantityAddRoute
  AuthenticatedAdminProductsQuantityUpdateRoute: typeof AuthenticatedAdminProductsQuantityUpdateRoute
}

const AuthenticatedAdminProductsRouteRouteChildren: AuthenticatedAdminProductsRouteRouteChildren =
  {
    AuthenticatedAdminProductsAddRoute: AuthenticatedAdminProductsAddRoute,
    AuthenticatedAdminProductsTrashRoute: AuthenticatedAdminProductsTrashRoute,
    AuthenticatedAdminProductsIndexRoute: AuthenticatedAdminProductsIndexRoute,
    AuthenticatedAdminProductsEditIdRoute:
      AuthenticatedAdminProductsEditIdRoute,
    AuthenticatedAdminProductsQuantityAddRoute:
      AuthenticatedAdminProductsQuantityAddRoute,
    AuthenticatedAdminProductsQuantityUpdateRoute:
      AuthenticatedAdminProductsQuantityUpdateRoute,
  }

const AuthenticatedAdminProductsRouteRouteWithChildren =
  AuthenticatedAdminProductsRouteRoute._addFileChildren(
    AuthenticatedAdminProductsRouteRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminProductsRouteRoute: typeof AuthenticatedAdminProductsRouteRouteWithChildren
  AuthenticatedAdminAboutRoute: typeof AuthenticatedAdminAboutRoute
  AuthenticatedAdminActivityHistoryRoute: typeof AuthenticatedAdminActivityHistoryRoute
  AuthenticatedAdminActivityScheduleRoute: typeof AuthenticatedAdminActivityScheduleRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminAttendancesHistoryRoute: typeof AuthenticatedAdminAttendancesHistoryRoute
  AuthenticatedAdminAttendancesRecordRoute: typeof AuthenticatedAdminAttendancesRecordRoute
  AuthenticatedAdminEmployeesAddRoute: typeof AuthenticatedAdminEmployeesAddRoute
  AuthenticatedAdminPlansMaterialRoute: typeof AuthenticatedAdminPlansMaterialRoute
  AuthenticatedAdminPlansProductionRoute: typeof AuthenticatedAdminPlansProductionRoute
  AuthenticatedAdminStampsBagRoute: typeof AuthenticatedAdminStampsBagRoute
  AuthenticatedAdminStampsBoxRoute: typeof AuthenticatedAdminStampsBoxRoute
  AuthenticatedAdminStampsHistoryRoute: typeof AuthenticatedAdminStampsHistoryRoute
  AuthenticatedAdminStampsRequestRoute: typeof AuthenticatedAdminStampsRequestRoute
  AuthenticatedAdminWorkSchedulesIdRoute: typeof AuthenticatedAdminWorkSchedulesIdRoute
  AuthenticatedAdminSalariesIdLazyRoute: typeof AuthenticatedAdminSalariesIdLazyRoute
  AuthenticatedAdminCheckPoIndexRoute: typeof AuthenticatedAdminCheckPoIndexRoute
  AuthenticatedAdminEmployeesIndexRoute: typeof AuthenticatedAdminEmployeesIndexRoute
  AuthenticatedAdminRolesIndexRoute: typeof AuthenticatedAdminRolesIndexRoute
  AuthenticatedAdminSalariesIndexRoute: typeof AuthenticatedAdminSalariesIndexRoute
  AuthenticatedAdminWorkScheduleCategoriesIndexRoute: typeof AuthenticatedAdminWorkScheduleCategoriesIndexRoute
  AuthenticatedAdminWorkSchedulesIndexRoute: typeof AuthenticatedAdminWorkSchedulesIndexRoute
  AuthenticatedAdminEmployeesEditIdRoute: typeof AuthenticatedAdminEmployeesEditIdRoute
  AuthenticatedAdminEmployeesTrashIndexRoute: typeof AuthenticatedAdminEmployeesTrashIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminProductsRouteRoute:
      AuthenticatedAdminProductsRouteRouteWithChildren,
    AuthenticatedAdminAboutRoute: AuthenticatedAdminAboutRoute,
    AuthenticatedAdminActivityHistoryRoute:
      AuthenticatedAdminActivityHistoryRoute,
    AuthenticatedAdminActivityScheduleRoute:
      AuthenticatedAdminActivityScheduleRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminAttendancesHistoryRoute:
      AuthenticatedAdminAttendancesHistoryRoute,
    AuthenticatedAdminAttendancesRecordRoute:
      AuthenticatedAdminAttendancesRecordRoute,
    AuthenticatedAdminEmployeesAddRoute: AuthenticatedAdminEmployeesAddRoute,
    AuthenticatedAdminPlansMaterialRoute: AuthenticatedAdminPlansMaterialRoute,
    AuthenticatedAdminPlansProductionRoute:
      AuthenticatedAdminPlansProductionRoute,
    AuthenticatedAdminStampsBagRoute: AuthenticatedAdminStampsBagRoute,
    AuthenticatedAdminStampsBoxRoute: AuthenticatedAdminStampsBoxRoute,
    AuthenticatedAdminStampsHistoryRoute: AuthenticatedAdminStampsHistoryRoute,
    AuthenticatedAdminStampsRequestRoute: AuthenticatedAdminStampsRequestRoute,
    AuthenticatedAdminWorkSchedulesIdRoute:
      AuthenticatedAdminWorkSchedulesIdRoute,
    AuthenticatedAdminSalariesIdLazyRoute:
      AuthenticatedAdminSalariesIdLazyRoute,
    AuthenticatedAdminCheckPoIndexRoute: AuthenticatedAdminCheckPoIndexRoute,
    AuthenticatedAdminEmployeesIndexRoute:
      AuthenticatedAdminEmployeesIndexRoute,
    AuthenticatedAdminRolesIndexRoute: AuthenticatedAdminRolesIndexRoute,
    AuthenticatedAdminSalariesIndexRoute: AuthenticatedAdminSalariesIndexRoute,
    AuthenticatedAdminWorkScheduleCategoriesIndexRoute:
      AuthenticatedAdminWorkScheduleCategoriesIndexRoute,
    AuthenticatedAdminWorkSchedulesIndexRoute:
      AuthenticatedAdminWorkSchedulesIndexRoute,
    AuthenticatedAdminEmployeesEditIdRoute:
      AuthenticatedAdminEmployeesEditIdRoute,
    AuthenticatedAdminEmployeesTrashIndexRoute:
      AuthenticatedAdminEmployeesTrashIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedEmployeeRouteRouteChildren {
  AuthenticatedEmployeeIndexRoute: typeof AuthenticatedEmployeeIndexRoute
  AuthenticatedEmployeeSalariesIdRoute: typeof AuthenticatedEmployeeSalariesIdRoute
  AuthenticatedEmployeeSchedulesIdRoute: typeof AuthenticatedEmployeeSchedulesIdRoute
  AuthenticatedEmployeeStampsRequestRoute: typeof AuthenticatedEmployeeStampsRequestRoute
  AuthenticatedEmployeeTodoAddProductRoute: typeof AuthenticatedEmployeeTodoAddProductRoute
  AuthenticatedEmployeeTodoHistoryRoute: typeof AuthenticatedEmployeeTodoHistoryRoute
  AuthenticatedEmployeeTodoUpdateQuantityRoute: typeof AuthenticatedEmployeeTodoUpdateQuantityRoute
  AuthenticatedEmployeeTodoUpdateQuantityErrorRoute: typeof AuthenticatedEmployeeTodoUpdateQuantityErrorRoute
  AuthenticatedEmployeeActivityScheduleIndexRoute: typeof AuthenticatedEmployeeActivityScheduleIndexRoute
  AuthenticatedEmployeeSalariesIndexRoute: typeof AuthenticatedEmployeeSalariesIndexRoute
  AuthenticatedEmployeeSchedulesIndexRoute: typeof AuthenticatedEmployeeSchedulesIndexRoute
  AuthenticatedEmployeeAttendancesCalculateIndexRoute: typeof AuthenticatedEmployeeAttendancesCalculateIndexRoute
  AuthenticatedEmployeeAttendancesHistoryIndexRoute: typeof AuthenticatedEmployeeAttendancesHistoryIndexRoute
}

const AuthenticatedEmployeeRouteRouteChildren: AuthenticatedEmployeeRouteRouteChildren =
  {
    AuthenticatedEmployeeIndexRoute: AuthenticatedEmployeeIndexRoute,
    AuthenticatedEmployeeSalariesIdRoute: AuthenticatedEmployeeSalariesIdRoute,
    AuthenticatedEmployeeSchedulesIdRoute:
      AuthenticatedEmployeeSchedulesIdRoute,
    AuthenticatedEmployeeStampsRequestRoute:
      AuthenticatedEmployeeStampsRequestRoute,
    AuthenticatedEmployeeTodoAddProductRoute:
      AuthenticatedEmployeeTodoAddProductRoute,
    AuthenticatedEmployeeTodoHistoryRoute:
      AuthenticatedEmployeeTodoHistoryRoute,
    AuthenticatedEmployeeTodoUpdateQuantityRoute:
      AuthenticatedEmployeeTodoUpdateQuantityRoute,
    AuthenticatedEmployeeTodoUpdateQuantityErrorRoute:
      AuthenticatedEmployeeTodoUpdateQuantityErrorRoute,
    AuthenticatedEmployeeActivityScheduleIndexRoute:
      AuthenticatedEmployeeActivityScheduleIndexRoute,
    AuthenticatedEmployeeSalariesIndexRoute:
      AuthenticatedEmployeeSalariesIndexRoute,
    AuthenticatedEmployeeSchedulesIndexRoute:
      AuthenticatedEmployeeSchedulesIndexRoute,
    AuthenticatedEmployeeAttendancesCalculateIndexRoute:
      AuthenticatedEmployeeAttendancesCalculateIndexRoute,
    AuthenticatedEmployeeAttendancesHistoryIndexRoute:
      AuthenticatedEmployeeAttendancesHistoryIndexRoute,
  }

const AuthenticatedEmployeeRouteRouteWithChildren =
  AuthenticatedEmployeeRouteRoute._addFileChildren(
    AuthenticatedEmployeeRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedEmployeeRouteRoute: typeof AuthenticatedEmployeeRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedEmployeeRouteRoute: AuthenticatedEmployeeRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/employee': typeof AuthenticatedEmployeeRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/admin/products': typeof AuthenticatedAdminProductsRouteRouteWithChildren
  '/admin/about': typeof AuthenticatedAdminAboutRoute
  '/admin/activity-history': typeof AuthenticatedAdminActivityHistoryRoute
  '/admin/activity-schedule': typeof AuthenticatedAdminActivityScheduleRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/employee/': typeof AuthenticatedEmployeeIndexRoute
  '/admin/attendances/history': typeof AuthenticatedAdminAttendancesHistoryRoute
  '/admin/attendances/record': typeof AuthenticatedAdminAttendancesRecordRoute
  '/admin/employees/add': typeof AuthenticatedAdminEmployeesAddRoute
  '/admin/plans/material': typeof AuthenticatedAdminPlansMaterialRoute
  '/admin/plans/production': typeof AuthenticatedAdminPlansProductionRoute
  '/admin/products/add': typeof AuthenticatedAdminProductsAddRoute
  '/admin/products/trash': typeof AuthenticatedAdminProductsTrashRoute
  '/admin/stamps/bag': typeof AuthenticatedAdminStampsBagRoute
  '/admin/stamps/box': typeof AuthenticatedAdminStampsBoxRoute
  '/admin/stamps/history': typeof AuthenticatedAdminStampsHistoryRoute
  '/admin/stamps/request': typeof AuthenticatedAdminStampsRequestRoute
  '/admin/work-schedules/$id': typeof AuthenticatedAdminWorkSchedulesIdRoute
  '/employee/salaries/$id': typeof AuthenticatedEmployeeSalariesIdRoute
  '/employee/schedules/$id': typeof AuthenticatedEmployeeSchedulesIdRoute
  '/employee/stamps/request': typeof AuthenticatedEmployeeStampsRequestRoute
  '/employee/todo/add-product': typeof AuthenticatedEmployeeTodoAddProductRoute
  '/employee/todo/history': typeof AuthenticatedEmployeeTodoHistoryRoute
  '/employee/todo/update-quantity': typeof AuthenticatedEmployeeTodoUpdateQuantityRoute
  '/employee/todo/update-quantity-error': typeof AuthenticatedEmployeeTodoUpdateQuantityErrorRoute
  '/admin/salaries/$id': typeof AuthenticatedAdminSalariesIdLazyRoute
  '/admin/check-po': typeof AuthenticatedAdminCheckPoIndexRoute
  '/admin/employees': typeof AuthenticatedAdminEmployeesIndexRoute
  '/admin/products/': typeof AuthenticatedAdminProductsIndexRoute
  '/admin/roles': typeof AuthenticatedAdminRolesIndexRoute
  '/admin/salaries': typeof AuthenticatedAdminSalariesIndexRoute
  '/admin/work-schedule-categories': typeof AuthenticatedAdminWorkScheduleCategoriesIndexRoute
  '/admin/work-schedules': typeof AuthenticatedAdminWorkSchedulesIndexRoute
  '/employee/activity-schedule': typeof AuthenticatedEmployeeActivityScheduleIndexRoute
  '/employee/salaries': typeof AuthenticatedEmployeeSalariesIndexRoute
  '/employee/schedules': typeof AuthenticatedEmployeeSchedulesIndexRoute
  '/admin/employees/edit/$id': typeof AuthenticatedAdminEmployeesEditIdRoute
  '/admin/products/edit/$id': typeof AuthenticatedAdminProductsEditIdRoute
  '/admin/products/quantity/add': typeof AuthenticatedAdminProductsQuantityAddRoute
  '/admin/products/quantity/update': typeof AuthenticatedAdminProductsQuantityUpdateRoute
  '/admin/employees/trash': typeof AuthenticatedAdminEmployeesTrashIndexRoute
  '/employee/attendances/calculate': typeof AuthenticatedEmployeeAttendancesCalculateIndexRoute
  '/employee/attendances/history': typeof AuthenticatedEmployeeAttendancesHistoryIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof authLoginRoute
  '/admin/about': typeof AuthenticatedAdminAboutRoute
  '/admin/activity-history': typeof AuthenticatedAdminActivityHistoryRoute
  '/admin/activity-schedule': typeof AuthenticatedAdminActivityScheduleRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/employee': typeof AuthenticatedEmployeeIndexRoute
  '/admin/attendances/history': typeof AuthenticatedAdminAttendancesHistoryRoute
  '/admin/attendances/record': typeof AuthenticatedAdminAttendancesRecordRoute
  '/admin/employees/add': typeof AuthenticatedAdminEmployeesAddRoute
  '/admin/plans/material': typeof AuthenticatedAdminPlansMaterialRoute
  '/admin/plans/production': typeof AuthenticatedAdminPlansProductionRoute
  '/admin/products/add': typeof AuthenticatedAdminProductsAddRoute
  '/admin/products/trash': typeof AuthenticatedAdminProductsTrashRoute
  '/admin/stamps/bag': typeof AuthenticatedAdminStampsBagRoute
  '/admin/stamps/box': typeof AuthenticatedAdminStampsBoxRoute
  '/admin/stamps/history': typeof AuthenticatedAdminStampsHistoryRoute
  '/admin/stamps/request': typeof AuthenticatedAdminStampsRequestRoute
  '/admin/work-schedules/$id': typeof AuthenticatedAdminWorkSchedulesIdRoute
  '/employee/salaries/$id': typeof AuthenticatedEmployeeSalariesIdRoute
  '/employee/schedules/$id': typeof AuthenticatedEmployeeSchedulesIdRoute
  '/employee/stamps/request': typeof AuthenticatedEmployeeStampsRequestRoute
  '/employee/todo/add-product': typeof AuthenticatedEmployeeTodoAddProductRoute
  '/employee/todo/history': typeof AuthenticatedEmployeeTodoHistoryRoute
  '/employee/todo/update-quantity': typeof AuthenticatedEmployeeTodoUpdateQuantityRoute
  '/employee/todo/update-quantity-error': typeof AuthenticatedEmployeeTodoUpdateQuantityErrorRoute
  '/admin/salaries/$id': typeof AuthenticatedAdminSalariesIdLazyRoute
  '/admin/check-po': typeof AuthenticatedAdminCheckPoIndexRoute
  '/admin/employees': typeof AuthenticatedAdminEmployeesIndexRoute
  '/admin/products': typeof AuthenticatedAdminProductsIndexRoute
  '/admin/roles': typeof AuthenticatedAdminRolesIndexRoute
  '/admin/salaries': typeof AuthenticatedAdminSalariesIndexRoute
  '/admin/work-schedule-categories': typeof AuthenticatedAdminWorkScheduleCategoriesIndexRoute
  '/admin/work-schedules': typeof AuthenticatedAdminWorkSchedulesIndexRoute
  '/employee/activity-schedule': typeof AuthenticatedEmployeeActivityScheduleIndexRoute
  '/employee/salaries': typeof AuthenticatedEmployeeSalariesIndexRoute
  '/employee/schedules': typeof AuthenticatedEmployeeSchedulesIndexRoute
  '/admin/employees/edit/$id': typeof AuthenticatedAdminEmployeesEditIdRoute
  '/admin/products/edit/$id': typeof AuthenticatedAdminProductsEditIdRoute
  '/admin/products/quantity/add': typeof AuthenticatedAdminProductsQuantityAddRoute
  '/admin/products/quantity/update': typeof AuthenticatedAdminProductsQuantityUpdateRoute
  '/admin/employees/trash': typeof AuthenticatedAdminEmployeesTrashIndexRoute
  '/employee/attendances/calculate': typeof AuthenticatedEmployeeAttendancesCalculateIndexRoute
  '/employee/attendances/history': typeof AuthenticatedEmployeeAttendancesHistoryIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/employee': typeof AuthenticatedEmployeeRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRouteRouteWithChildren
  '/_authenticated/admin/about': typeof AuthenticatedAdminAboutRoute
  '/_authenticated/admin/activity-history': typeof AuthenticatedAdminActivityHistoryRoute
  '/_authenticated/admin/activity-schedule': typeof AuthenticatedAdminActivityScheduleRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/employee/': typeof AuthenticatedEmployeeIndexRoute
  '/_authenticated/admin/attendances/history': typeof AuthenticatedAdminAttendancesHistoryRoute
  '/_authenticated/admin/attendances/record': typeof AuthenticatedAdminAttendancesRecordRoute
  '/_authenticated/admin/employees/add': typeof AuthenticatedAdminEmployeesAddRoute
  '/_authenticated/admin/plans/material': typeof AuthenticatedAdminPlansMaterialRoute
  '/_authenticated/admin/plans/production': typeof AuthenticatedAdminPlansProductionRoute
  '/_authenticated/admin/products/add': typeof AuthenticatedAdminProductsAddRoute
  '/_authenticated/admin/products/trash': typeof AuthenticatedAdminProductsTrashRoute
  '/_authenticated/admin/stamps/bag': typeof AuthenticatedAdminStampsBagRoute
  '/_authenticated/admin/stamps/box': typeof AuthenticatedAdminStampsBoxRoute
  '/_authenticated/admin/stamps/history': typeof AuthenticatedAdminStampsHistoryRoute
  '/_authenticated/admin/stamps/request': typeof AuthenticatedAdminStampsRequestRoute
  '/_authenticated/admin/work-schedules/$id': typeof AuthenticatedAdminWorkSchedulesIdRoute
  '/_authenticated/employee/salaries/$id': typeof AuthenticatedEmployeeSalariesIdRoute
  '/_authenticated/employee/schedules/$id': typeof AuthenticatedEmployeeSchedulesIdRoute
  '/_authenticated/employee/stamps/request': typeof AuthenticatedEmployeeStampsRequestRoute
  '/_authenticated/employee/todo/add-product': typeof AuthenticatedEmployeeTodoAddProductRoute
  '/_authenticated/employee/todo/history': typeof AuthenticatedEmployeeTodoHistoryRoute
  '/_authenticated/employee/todo/update-quantity': typeof AuthenticatedEmployeeTodoUpdateQuantityRoute
  '/_authenticated/employee/todo/update-quantity-error': typeof AuthenticatedEmployeeTodoUpdateQuantityErrorRoute
  '/_authenticated/admin/salaries/$id': typeof AuthenticatedAdminSalariesIdLazyRoute
  '/_authenticated/admin/check-po/': typeof AuthenticatedAdminCheckPoIndexRoute
  '/_authenticated/admin/employees/': typeof AuthenticatedAdminEmployeesIndexRoute
  '/_authenticated/admin/products/': typeof AuthenticatedAdminProductsIndexRoute
  '/_authenticated/admin/roles/': typeof AuthenticatedAdminRolesIndexRoute
  '/_authenticated/admin/salaries/': typeof AuthenticatedAdminSalariesIndexRoute
  '/_authenticated/admin/work-schedule-categories/': typeof AuthenticatedAdminWorkScheduleCategoriesIndexRoute
  '/_authenticated/admin/work-schedules/': typeof AuthenticatedAdminWorkSchedulesIndexRoute
  '/_authenticated/employee/activity-schedule/': typeof AuthenticatedEmployeeActivityScheduleIndexRoute
  '/_authenticated/employee/salaries/': typeof AuthenticatedEmployeeSalariesIndexRoute
  '/_authenticated/employee/schedules/': typeof AuthenticatedEmployeeSchedulesIndexRoute
  '/_authenticated/admin/employees/edit/$id': typeof AuthenticatedAdminEmployeesEditIdRoute
  '/_authenticated/admin/products/edit/$id': typeof AuthenticatedAdminProductsEditIdRoute
  '/_authenticated/admin/products/quantity/add': typeof AuthenticatedAdminProductsQuantityAddRoute
  '/_authenticated/admin/products/quantity/update': typeof AuthenticatedAdminProductsQuantityUpdateRoute
  '/_authenticated/admin/employees/trash/': typeof AuthenticatedAdminEmployeesTrashIndexRoute
  '/_authenticated/employee/attendances/calculate/': typeof AuthenticatedEmployeeAttendancesCalculateIndexRoute
  '/_authenticated/employee/attendances/history/': typeof AuthenticatedEmployeeAttendancesHistoryIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/forbidden'
    | '/admin'
    | '/employee'
    | '/login'
    | '/admin/products'
    | '/admin/about'
    | '/admin/activity-history'
    | '/admin/activity-schedule'
    | '/admin/'
    | '/employee/'
    | '/admin/attendances/history'
    | '/admin/attendances/record'
    | '/admin/employees/add'
    | '/admin/plans/material'
    | '/admin/plans/production'
    | '/admin/products/add'
    | '/admin/products/trash'
    | '/admin/stamps/bag'
    | '/admin/stamps/box'
    | '/admin/stamps/history'
    | '/admin/stamps/request'
    | '/admin/work-schedules/$id'
    | '/employee/salaries/$id'
    | '/employee/schedules/$id'
    | '/employee/stamps/request'
    | '/employee/todo/add-product'
    | '/employee/todo/history'
    | '/employee/todo/update-quantity'
    | '/employee/todo/update-quantity-error'
    | '/admin/salaries/$id'
    | '/admin/check-po'
    | '/admin/employees'
    | '/admin/products/'
    | '/admin/roles'
    | '/admin/salaries'
    | '/admin/work-schedule-categories'
    | '/admin/work-schedules'
    | '/employee/activity-schedule'
    | '/employee/salaries'
    | '/employee/schedules'
    | '/admin/employees/edit/$id'
    | '/admin/products/edit/$id'
    | '/admin/products/quantity/add'
    | '/admin/products/quantity/update'
    | '/admin/employees/trash'
    | '/employee/attendances/calculate'
    | '/employee/attendances/history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forbidden'
    | '/login'
    | '/admin/about'
    | '/admin/activity-history'
    | '/admin/activity-schedule'
    | '/admin'
    | '/employee'
    | '/admin/attendances/history'
    | '/admin/attendances/record'
    | '/admin/employees/add'
    | '/admin/plans/material'
    | '/admin/plans/production'
    | '/admin/products/add'
    | '/admin/products/trash'
    | '/admin/stamps/bag'
    | '/admin/stamps/box'
    | '/admin/stamps/history'
    | '/admin/stamps/request'
    | '/admin/work-schedules/$id'
    | '/employee/salaries/$id'
    | '/employee/schedules/$id'
    | '/employee/stamps/request'
    | '/employee/todo/add-product'
    | '/employee/todo/history'
    | '/employee/todo/update-quantity'
    | '/employee/todo/update-quantity-error'
    | '/admin/salaries/$id'
    | '/admin/check-po'
    | '/admin/employees'
    | '/admin/products'
    | '/admin/roles'
    | '/admin/salaries'
    | '/admin/work-schedule-categories'
    | '/admin/work-schedules'
    | '/employee/activity-schedule'
    | '/employee/salaries'
    | '/employee/schedules'
    | '/admin/employees/edit/$id'
    | '/admin/products/edit/$id'
    | '/admin/products/quantity/add'
    | '/admin/products/quantity/update'
    | '/admin/employees/trash'
    | '/employee/attendances/calculate'
    | '/employee/attendances/history'
  id:
    | '__root__'
    | '/(auth)'
    | '/_authenticated'
    | '/forbidden'
    | '/_authenticated/admin'
    | '/_authenticated/employee'
    | '/(auth)/login'
    | '/_authenticated/'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/about'
    | '/_authenticated/admin/activity-history'
    | '/_authenticated/admin/activity-schedule'
    | '/_authenticated/admin/'
    | '/_authenticated/employee/'
    | '/_authenticated/admin/attendances/history'
    | '/_authenticated/admin/attendances/record'
    | '/_authenticated/admin/employees/add'
    | '/_authenticated/admin/plans/material'
    | '/_authenticated/admin/plans/production'
    | '/_authenticated/admin/products/add'
    | '/_authenticated/admin/products/trash'
    | '/_authenticated/admin/stamps/bag'
    | '/_authenticated/admin/stamps/box'
    | '/_authenticated/admin/stamps/history'
    | '/_authenticated/admin/stamps/request'
    | '/_authenticated/admin/work-schedules/$id'
    | '/_authenticated/employee/salaries/$id'
    | '/_authenticated/employee/schedules/$id'
    | '/_authenticated/employee/stamps/request'
    | '/_authenticated/employee/todo/add-product'
    | '/_authenticated/employee/todo/history'
    | '/_authenticated/employee/todo/update-quantity'
    | '/_authenticated/employee/todo/update-quantity-error'
    | '/_authenticated/admin/salaries/$id'
    | '/_authenticated/admin/check-po/'
    | '/_authenticated/admin/employees/'
    | '/_authenticated/admin/products/'
    | '/_authenticated/admin/roles/'
    | '/_authenticated/admin/salaries/'
    | '/_authenticated/admin/work-schedule-categories/'
    | '/_authenticated/admin/work-schedules/'
    | '/_authenticated/employee/activity-schedule/'
    | '/_authenticated/employee/salaries/'
    | '/_authenticated/employee/schedules/'
    | '/_authenticated/admin/employees/edit/$id'
    | '/_authenticated/admin/products/edit/$id'
    | '/_authenticated/admin/products/quantity/add'
    | '/_authenticated/admin/products/quantity/update'
    | '/_authenticated/admin/employees/trash/'
    | '/_authenticated/employee/attendances/calculate/'
    | '/_authenticated/employee/attendances/history/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForbiddenRoute: typeof ForbiddenRoute
}

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForbiddenRoute: ForbiddenRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(auth)",
        "/_authenticated",
        "/forbidden"
      ]
    },
    "/(auth)": {
      "filePath": "(auth)/route.tsx",
      "children": [
        "/(auth)/login"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/admin",
        "/_authenticated/employee",
        "/_authenticated/"
      ]
    },
    "/forbidden": {
      "filePath": "forbidden.tsx"
    },
    "/_authenticated/admin": {
      "filePath": "_authenticated/admin/route.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/admin/products",
        "/_authenticated/admin/about",
        "/_authenticated/admin/activity-history",
        "/_authenticated/admin/activity-schedule",
        "/_authenticated/admin/",
        "/_authenticated/admin/attendances/history",
        "/_authenticated/admin/attendances/record",
        "/_authenticated/admin/employees/add",
        "/_authenticated/admin/plans/material",
        "/_authenticated/admin/plans/production",
        "/_authenticated/admin/stamps/bag",
        "/_authenticated/admin/stamps/box",
        "/_authenticated/admin/stamps/history",
        "/_authenticated/admin/stamps/request",
        "/_authenticated/admin/work-schedules/$id",
        "/_authenticated/admin/salaries/$id",
        "/_authenticated/admin/check-po/",
        "/_authenticated/admin/employees/",
        "/_authenticated/admin/roles/",
        "/_authenticated/admin/salaries/",
        "/_authenticated/admin/work-schedule-categories/",
        "/_authenticated/admin/work-schedules/",
        "/_authenticated/admin/employees/edit/$id",
        "/_authenticated/admin/employees/trash/"
      ]
    },
    "/_authenticated/employee": {
      "filePath": "_authenticated/employee/route.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/employee/",
        "/_authenticated/employee/salaries/$id",
        "/_authenticated/employee/schedules/$id",
        "/_authenticated/employee/stamps/request",
        "/_authenticated/employee/todo/add-product",
        "/_authenticated/employee/todo/history",
        "/_authenticated/employee/todo/update-quantity",
        "/_authenticated/employee/todo/update-quantity-error",
        "/_authenticated/employee/activity-schedule/",
        "/_authenticated/employee/salaries/",
        "/_authenticated/employee/schedules/",
        "/_authenticated/employee/attendances/calculate/",
        "/_authenticated/employee/attendances/history/"
      ]
    },
    "/(auth)/login": {
      "filePath": "(auth)/login.tsx",
      "parent": "/(auth)"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/products": {
      "filePath": "_authenticated/admin/products/route.tsx",
      "parent": "/_authenticated/admin",
      "children": [
        "/_authenticated/admin/products/add",
        "/_authenticated/admin/products/trash",
        "/_authenticated/admin/products/",
        "/_authenticated/admin/products/edit/$id",
        "/_authenticated/admin/products/quantity/add",
        "/_authenticated/admin/products/quantity/update"
      ]
    },
    "/_authenticated/admin/about": {
      "filePath": "_authenticated/admin/about.tsx",
      "parent": "/_authenticated/admin"
    },
    "/_authenticated/admin/activity-history": {
      "filePath": "_authenticated/admin/activity-history.tsx",
      "parent": "/_authenticated/admin"
    },
    "/_authenticated/admin/activity-schedule": {
      "filePath": "_authenticated/admin/activity-schedule.tsx",
      "parent": "/_authenticated/admin"
    },
    "/_authenticated/admin/": {
      "filePath": "_authenticated/admin/index.tsx",
      "parent": "/_authenticated/admin"
    },
    "/_authenticated/employee/": {
      "filePath": "_authenticated/employee/index.tsx",
      "parent": "/_authenticated/employee"
    },
    "/_authenticated/admin/attendances/history": {
      "filePath": "_authenticated/admin/attendances/history.tsx",
      "parent": "/_authenticated/admin"
    },
    "/_authenticated/admin/attendances/record": {
      "filePath": "_authenticated/admin/attendances/record.tsx",
      "parent": "/_authenticated/admin"
    },
    "/_authenticated/admin/employees/add": {
      "filePath": "_authenticated/admin/employees/add.tsx",
      "parent": "/_authenticated/admin"
    },
    "/_authenticated/admin/plans/material": {
      "filePath": "_authenticated/admin/plans/material.tsx",
      "parent": "/_authenticated/admin"
    },
    "/_authenticated/admin/plans/production": {
      "filePath": "_authenticated/admin/plans/production.tsx",
      "parent": "/_authenticated/admin"
    },
    "/_authenticated/admin/products/add": {
      "filePath": "_authenticated/admin/products/add.tsx",
      "parent": "/_authenticated/admin/products"
    },
    "/_authenticated/admin/products/trash": {
      "filePath": "_authenticated/admin/products/trash.tsx",
      "parent": "/_authenticated/admin/products"
    },
    "/_authenticated/admin/stamps/bag": {
      "filePath": "_authenticated/admin/stamps/bag.tsx",
      "parent": "/_authenticated/admin"
    },
    "/_authenticated/admin/stamps/box": {
      "filePath": "_authenticated/admin/stamps/box.tsx",
      "parent": "/_authenticated/admin"
    },
    "/_authenticated/admin/stamps/history": {
      "filePath": "_authenticated/admin/stamps/history.tsx",
      "parent": "/_authenticated/admin"
    },
    "/_authenticated/admin/stamps/request": {
      "filePath": "_authenticated/admin/stamps/request.tsx",
      "parent": "/_authenticated/admin"
    },
    "/_authenticated/admin/work-schedules/$id": {
      "filePath": "_authenticated/admin/work-schedules/$id.tsx",
      "parent": "/_authenticated/admin"
    },
    "/_authenticated/employee/salaries/$id": {
      "filePath": "_authenticated/employee/salaries/$id.tsx",
      "parent": "/_authenticated/employee"
    },
    "/_authenticated/employee/schedules/$id": {
      "filePath": "_authenticated/employee/schedules/$id.tsx",
      "parent": "/_authenticated/employee"
    },
    "/_authenticated/employee/stamps/request": {
      "filePath": "_authenticated/employee/stamps/request.tsx",
      "parent": "/_authenticated/employee"
    },
    "/_authenticated/employee/todo/add-product": {
      "filePath": "_authenticated/employee/todo/add-product.tsx",
      "parent": "/_authenticated/employee"
    },
    "/_authenticated/employee/todo/history": {
      "filePath": "_authenticated/employee/todo/history.tsx",
      "parent": "/_authenticated/employee"
    },
    "/_authenticated/employee/todo/update-quantity": {
      "filePath": "_authenticated/employee/todo/update-quantity.tsx",
      "parent": "/_authenticated/employee"
    },
    "/_authenticated/employee/todo/update-quantity-error": {
      "filePath": "_authenticated/employee/todo/update-quantity-error.tsx",
      "parent": "/_authenticated/employee"
    },
    "/_authenticated/admin/salaries/$id": {
      "filePath": "_authenticated/admin/salaries/$id.lazy.tsx",
      "parent": "/_authenticated/admin"
    },
    "/_authenticated/admin/check-po/": {
      "filePath": "_authenticated/admin/check-po/index.tsx",
      "parent": "/_authenticated/admin"
    },
    "/_authenticated/admin/employees/": {
      "filePath": "_authenticated/admin/employees/index.tsx",
      "parent": "/_authenticated/admin"
    },
    "/_authenticated/admin/products/": {
      "filePath": "_authenticated/admin/products/index.tsx",
      "parent": "/_authenticated/admin/products"
    },
    "/_authenticated/admin/roles/": {
      "filePath": "_authenticated/admin/roles/index.tsx",
      "parent": "/_authenticated/admin"
    },
    "/_authenticated/admin/salaries/": {
      "filePath": "_authenticated/admin/salaries/index.tsx",
      "parent": "/_authenticated/admin"
    },
    "/_authenticated/admin/work-schedule-categories/": {
      "filePath": "_authenticated/admin/work-schedule-categories/index.tsx",
      "parent": "/_authenticated/admin"
    },
    "/_authenticated/admin/work-schedules/": {
      "filePath": "_authenticated/admin/work-schedules/index.tsx",
      "parent": "/_authenticated/admin"
    },
    "/_authenticated/employee/activity-schedule/": {
      "filePath": "_authenticated/employee/activity-schedule/index.tsx",
      "parent": "/_authenticated/employee"
    },
    "/_authenticated/employee/salaries/": {
      "filePath": "_authenticated/employee/salaries/index.tsx",
      "parent": "/_authenticated/employee"
    },
    "/_authenticated/employee/schedules/": {
      "filePath": "_authenticated/employee/schedules/index.tsx",
      "parent": "/_authenticated/employee"
    },
    "/_authenticated/admin/employees/edit/$id": {
      "filePath": "_authenticated/admin/employees/edit.$id.tsx",
      "parent": "/_authenticated/admin"
    },
    "/_authenticated/admin/products/edit/$id": {
      "filePath": "_authenticated/admin/products/edit.$id.tsx",
      "parent": "/_authenticated/admin/products"
    },
    "/_authenticated/admin/products/quantity/add": {
      "filePath": "_authenticated/admin/products/quantity/add.tsx",
      "parent": "/_authenticated/admin/products"
    },
    "/_authenticated/admin/products/quantity/update": {
      "filePath": "_authenticated/admin/products/quantity/update.tsx",
      "parent": "/_authenticated/admin/products"
    },
    "/_authenticated/admin/employees/trash/": {
      "filePath": "_authenticated/admin/employees/trash/index.tsx",
      "parent": "/_authenticated/admin"
    },
    "/_authenticated/employee/attendances/calculate/": {
      "filePath": "_authenticated/employee/attendances/calculate/index.tsx",
      "parent": "/_authenticated/employee"
    },
    "/_authenticated/employee/attendances/history/": {
      "filePath": "_authenticated/employee/attendances/history/index.tsx",
      "parent": "/_authenticated/employee"
    }
  }
}
ROUTE_MANIFEST_END */
