/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as authRouteImport } from './routes/(auth)/route'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as authLoginImport } from './routes/(auth)/login'
import { Route as AuthenticatedEmployeeIndexImport } from './routes/_authenticated/employee/index'
import { Route as AuthenticatedAdminIndexImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminCheckPoImport } from './routes/_authenticated/admin/check-po'
import { Route as AuthenticatedAdminActivityScheduleImport } from './routes/_authenticated/admin/activity-schedule'
import { Route as AuthenticatedAdminActivityHistoryImport } from './routes/_authenticated/admin/activity-history'
import { Route as AuthenticatedAdminAboutImport } from './routes/_authenticated/admin/about'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin/products/route'
import { Route as AuthenticatedAdminWorkSchedulesIndexImport } from './routes/_authenticated/admin/work-schedules/index'
import { Route as AuthenticatedAdminWorkScheduleCategoriesIndexImport } from './routes/_authenticated/admin/work-schedule-categories/index'
import { Route as AuthenticatedAdminSalariesIndexImport } from './routes/_authenticated/admin/salaries/index'
import { Route as AuthenticatedAdminRolesIndexImport } from './routes/_authenticated/admin/roles/index'
import { Route as AuthenticatedAdminProductsIndexImport } from './routes/_authenticated/admin/products/index'
import { Route as AuthenticatedAdminEmployeesIndexImport } from './routes/_authenticated/admin/employees/index'
import { Route as AuthenticatedAdminWorkSchedulesIdImport } from './routes/_authenticated/admin/work-schedules/$id'
import { Route as AuthenticatedAdminStampsRequestImport } from './routes/_authenticated/admin/stamps/request'
import { Route as AuthenticatedAdminStampsHistoryImport } from './routes/_authenticated/admin/stamps/history'
import { Route as AuthenticatedAdminStampsBoxImport } from './routes/_authenticated/admin/stamps/box'
import { Route as AuthenticatedAdminStampsBagImport } from './routes/_authenticated/admin/stamps/bag'
import { Route as AuthenticatedAdminProductsTrashImport } from './routes/_authenticated/admin/products/trash'
import { Route as AuthenticatedAdminProductsAddImport } from './routes/_authenticated/admin/products/add'
import { Route as AuthenticatedAdminPlansProductionImport } from './routes/_authenticated/admin/plans/production'
import { Route as AuthenticatedAdminPlansMaterialImport } from './routes/_authenticated/admin/plans/material'
import { Route as AuthenticatedAdminEmployeesAddImport } from './routes/_authenticated/admin/employees/add'
import { Route as AuthenticatedAdminAttendancesSheetImport } from './routes/_authenticated/admin/attendances/sheet'
import { Route as AuthenticatedAdminAttendancesHistoryImport } from './routes/_authenticated/admin/attendances/history'
import { Route as AuthenticatedAdminEmployeesTrashIndexImport } from './routes/_authenticated/admin/employees/trash/index'
import { Route as AuthenticatedAdminProductsQuantityUpdateImport } from './routes/_authenticated/admin/products/quantity/update'
import { Route as AuthenticatedAdminProductsEditIdImport } from './routes/_authenticated/admin/products/edit.$id'
import { Route as AuthenticatedAdminEmployeesEditIdImport } from './routes/_authenticated/admin/employees/edit.$id'

// Create Virtual Routes

const AuthenticatedAdminSalariesIdLazyImport = createFileRoute(
  '/_authenticated/admin/salaries/$id',
)()

// Create/Update Routes

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const authRouteRoute = authRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const authLoginRoute = authLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)

const AuthenticatedEmployeeIndexRoute = AuthenticatedEmployeeIndexImport.update(
  {
    id: '/employee/',
    path: '/employee/',
    getParentRoute: () => AuthenticatedRoute,
  } as any,
)

const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedAdminCheckPoRoute = AuthenticatedAdminCheckPoImport.update({
  id: '/admin/check-po',
  path: '/admin/check-po',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedAdminActivityScheduleRoute =
  AuthenticatedAdminActivityScheduleImport.update({
    id: '/admin/activity-schedule',
    path: '/admin/activity-schedule',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedAdminActivityHistoryRoute =
  AuthenticatedAdminActivityHistoryImport.update({
    id: '/admin/activity-history',
    path: '/admin/activity-history',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedAdminAboutRoute = AuthenticatedAdminAboutImport.update({
  id: '/admin/about',
  path: '/admin/about',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedAdminProductsRouteRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/admin/products',
    path: '/admin/products',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedAdminWorkSchedulesIndexRoute =
  AuthenticatedAdminWorkSchedulesIndexImport.update({
    id: '/admin/work-schedules/',
    path: '/admin/work-schedules/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedAdminWorkScheduleCategoriesIndexRoute =
  AuthenticatedAdminWorkScheduleCategoriesIndexImport.update({
    id: '/admin/work-schedule-categories/',
    path: '/admin/work-schedule-categories/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedAdminSalariesIndexRoute =
  AuthenticatedAdminSalariesIndexImport.update({
    id: '/admin/salaries/',
    path: '/admin/salaries/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedAdminRolesIndexRoute =
  AuthenticatedAdminRolesIndexImport.update({
    id: '/admin/roles/',
    path: '/admin/roles/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedAdminProductsIndexRoute =
  AuthenticatedAdminProductsIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminProductsRouteRoute,
  } as any)

const AuthenticatedAdminEmployeesIndexRoute =
  AuthenticatedAdminEmployeesIndexImport.update({
    id: '/admin/employees/',
    path: '/admin/employees/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedAdminSalariesIdLazyRoute =
  AuthenticatedAdminSalariesIdLazyImport.update({
    id: '/admin/salaries/$id',
    path: '/admin/salaries/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/admin/salaries/$id.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedAdminWorkSchedulesIdRoute =
  AuthenticatedAdminWorkSchedulesIdImport.update({
    id: '/admin/work-schedules/$id',
    path: '/admin/work-schedules/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedAdminStampsRequestRoute =
  AuthenticatedAdminStampsRequestImport.update({
    id: '/admin/stamps/request',
    path: '/admin/stamps/request',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedAdminStampsHistoryRoute =
  AuthenticatedAdminStampsHistoryImport.update({
    id: '/admin/stamps/history',
    path: '/admin/stamps/history',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedAdminStampsBoxRoute =
  AuthenticatedAdminStampsBoxImport.update({
    id: '/admin/stamps/box',
    path: '/admin/stamps/box',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedAdminStampsBagRoute =
  AuthenticatedAdminStampsBagImport.update({
    id: '/admin/stamps/bag',
    path: '/admin/stamps/bag',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedAdminProductsTrashRoute =
  AuthenticatedAdminProductsTrashImport.update({
    id: '/trash',
    path: '/trash',
    getParentRoute: () => AuthenticatedAdminProductsRouteRoute,
  } as any)

const AuthenticatedAdminProductsAddRoute =
  AuthenticatedAdminProductsAddImport.update({
    id: '/add',
    path: '/add',
    getParentRoute: () => AuthenticatedAdminProductsRouteRoute,
  } as any)

const AuthenticatedAdminPlansProductionRoute =
  AuthenticatedAdminPlansProductionImport.update({
    id: '/admin/plans/production',
    path: '/admin/plans/production',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedAdminPlansMaterialRoute =
  AuthenticatedAdminPlansMaterialImport.update({
    id: '/admin/plans/material',
    path: '/admin/plans/material',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedAdminEmployeesAddRoute =
  AuthenticatedAdminEmployeesAddImport.update({
    id: '/admin/employees/add',
    path: '/admin/employees/add',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedAdminAttendancesSheetRoute =
  AuthenticatedAdminAttendancesSheetImport.update({
    id: '/admin/attendances/sheet',
    path: '/admin/attendances/sheet',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedAdminAttendancesHistoryRoute =
  AuthenticatedAdminAttendancesHistoryImport.update({
    id: '/admin/attendances/history',
    path: '/admin/attendances/history',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedAdminEmployeesTrashIndexRoute =
  AuthenticatedAdminEmployeesTrashIndexImport.update({
    id: '/admin/employees/trash/',
    path: '/admin/employees/trash/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedAdminProductsQuantityUpdateRoute =
  AuthenticatedAdminProductsQuantityUpdateImport.update({
    id: '/quantity/update',
    path: '/quantity/update',
    getParentRoute: () => AuthenticatedAdminProductsRouteRoute,
  } as any)

const AuthenticatedAdminProductsEditIdRoute =
  AuthenticatedAdminProductsEditIdImport.update({
    id: '/edit/$id',
    path: '/edit/$id',
    getParentRoute: () => AuthenticatedAdminProductsRouteRoute,
  } as any)

const AuthenticatedAdminEmployeesEditIdRoute =
  AuthenticatedAdminEmployeesEditIdImport.update({
    id: '/admin/employees/edit/$id',
    path: '/admin/employees/edit/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authRouteImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginImport
      parentRoute: typeof authRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/admin/about': {
      id: '/_authenticated/admin/about'
      path: '/admin/about'
      fullPath: '/admin/about'
      preLoaderRoute: typeof AuthenticatedAdminAboutImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/admin/activity-history': {
      id: '/_authenticated/admin/activity-history'
      path: '/admin/activity-history'
      fullPath: '/admin/activity-history'
      preLoaderRoute: typeof AuthenticatedAdminActivityHistoryImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/admin/activity-schedule': {
      id: '/_authenticated/admin/activity-schedule'
      path: '/admin/activity-schedule'
      fullPath: '/admin/activity-schedule'
      preLoaderRoute: typeof AuthenticatedAdminActivityScheduleImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/admin/check-po': {
      id: '/_authenticated/admin/check-po'
      path: '/admin/check-po'
      fullPath: '/admin/check-po'
      preLoaderRoute: typeof AuthenticatedAdminCheckPoImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/employee/': {
      id: '/_authenticated/employee/'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof AuthenticatedEmployeeIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/admin/attendances/history': {
      id: '/_authenticated/admin/attendances/history'
      path: '/admin/attendances/history'
      fullPath: '/admin/attendances/history'
      preLoaderRoute: typeof AuthenticatedAdminAttendancesHistoryImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/admin/attendances/sheet': {
      id: '/_authenticated/admin/attendances/sheet'
      path: '/admin/attendances/sheet'
      fullPath: '/admin/attendances/sheet'
      preLoaderRoute: typeof AuthenticatedAdminAttendancesSheetImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/admin/employees/add': {
      id: '/_authenticated/admin/employees/add'
      path: '/admin/employees/add'
      fullPath: '/admin/employees/add'
      preLoaderRoute: typeof AuthenticatedAdminEmployeesAddImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/admin/plans/material': {
      id: '/_authenticated/admin/plans/material'
      path: '/admin/plans/material'
      fullPath: '/admin/plans/material'
      preLoaderRoute: typeof AuthenticatedAdminPlansMaterialImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/admin/plans/production': {
      id: '/_authenticated/admin/plans/production'
      path: '/admin/plans/production'
      fullPath: '/admin/plans/production'
      preLoaderRoute: typeof AuthenticatedAdminPlansProductionImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/admin/products/add': {
      id: '/_authenticated/admin/products/add'
      path: '/add'
      fullPath: '/admin/products/add'
      preLoaderRoute: typeof AuthenticatedAdminProductsAddImport
      parentRoute: typeof AuthenticatedAdminProductsRouteImport
    }
    '/_authenticated/admin/products/trash': {
      id: '/_authenticated/admin/products/trash'
      path: '/trash'
      fullPath: '/admin/products/trash'
      preLoaderRoute: typeof AuthenticatedAdminProductsTrashImport
      parentRoute: typeof AuthenticatedAdminProductsRouteImport
    }
    '/_authenticated/admin/stamps/bag': {
      id: '/_authenticated/admin/stamps/bag'
      path: '/admin/stamps/bag'
      fullPath: '/admin/stamps/bag'
      preLoaderRoute: typeof AuthenticatedAdminStampsBagImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/admin/stamps/box': {
      id: '/_authenticated/admin/stamps/box'
      path: '/admin/stamps/box'
      fullPath: '/admin/stamps/box'
      preLoaderRoute: typeof AuthenticatedAdminStampsBoxImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/admin/stamps/history': {
      id: '/_authenticated/admin/stamps/history'
      path: '/admin/stamps/history'
      fullPath: '/admin/stamps/history'
      preLoaderRoute: typeof AuthenticatedAdminStampsHistoryImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/admin/stamps/request': {
      id: '/_authenticated/admin/stamps/request'
      path: '/admin/stamps/request'
      fullPath: '/admin/stamps/request'
      preLoaderRoute: typeof AuthenticatedAdminStampsRequestImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/admin/work-schedules/$id': {
      id: '/_authenticated/admin/work-schedules/$id'
      path: '/admin/work-schedules/$id'
      fullPath: '/admin/work-schedules/$id'
      preLoaderRoute: typeof AuthenticatedAdminWorkSchedulesIdImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/admin/salaries/$id': {
      id: '/_authenticated/admin/salaries/$id'
      path: '/admin/salaries/$id'
      fullPath: '/admin/salaries/$id'
      preLoaderRoute: typeof AuthenticatedAdminSalariesIdLazyImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/admin/employees/': {
      id: '/_authenticated/admin/employees/'
      path: '/admin/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AuthenticatedAdminEmployeesIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/admin/products/': {
      id: '/_authenticated/admin/products/'
      path: '/'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AuthenticatedAdminProductsIndexImport
      parentRoute: typeof AuthenticatedAdminProductsRouteImport
    }
    '/_authenticated/admin/roles/': {
      id: '/_authenticated/admin/roles/'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/admin/salaries/': {
      id: '/_authenticated/admin/salaries/'
      path: '/admin/salaries'
      fullPath: '/admin/salaries'
      preLoaderRoute: typeof AuthenticatedAdminSalariesIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/admin/work-schedule-categories/': {
      id: '/_authenticated/admin/work-schedule-categories/'
      path: '/admin/work-schedule-categories'
      fullPath: '/admin/work-schedule-categories'
      preLoaderRoute: typeof AuthenticatedAdminWorkScheduleCategoriesIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/admin/work-schedules/': {
      id: '/_authenticated/admin/work-schedules/'
      path: '/admin/work-schedules'
      fullPath: '/admin/work-schedules'
      preLoaderRoute: typeof AuthenticatedAdminWorkSchedulesIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/admin/employees/edit/$id': {
      id: '/_authenticated/admin/employees/edit/$id'
      path: '/admin/employees/edit/$id'
      fullPath: '/admin/employees/edit/$id'
      preLoaderRoute: typeof AuthenticatedAdminEmployeesEditIdImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/admin/products/edit/$id': {
      id: '/_authenticated/admin/products/edit/$id'
      path: '/edit/$id'
      fullPath: '/admin/products/edit/$id'
      preLoaderRoute: typeof AuthenticatedAdminProductsEditIdImport
      parentRoute: typeof AuthenticatedAdminProductsRouteImport
    }
    '/_authenticated/admin/products/quantity/update': {
      id: '/_authenticated/admin/products/quantity/update'
      path: '/quantity/update'
      fullPath: '/admin/products/quantity/update'
      preLoaderRoute: typeof AuthenticatedAdminProductsQuantityUpdateImport
      parentRoute: typeof AuthenticatedAdminProductsRouteImport
    }
    '/_authenticated/admin/employees/trash/': {
      id: '/_authenticated/admin/employees/trash/'
      path: '/admin/employees/trash'
      fullPath: '/admin/employees/trash'
      preLoaderRoute: typeof AuthenticatedAdminEmployeesTrashIndexImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface AuthenticatedAdminProductsRouteRouteChildren {
  AuthenticatedAdminProductsAddRoute: typeof AuthenticatedAdminProductsAddRoute
  AuthenticatedAdminProductsTrashRoute: typeof AuthenticatedAdminProductsTrashRoute
  AuthenticatedAdminProductsIndexRoute: typeof AuthenticatedAdminProductsIndexRoute
  AuthenticatedAdminProductsEditIdRoute: typeof AuthenticatedAdminProductsEditIdRoute
  AuthenticatedAdminProductsQuantityUpdateRoute: typeof AuthenticatedAdminProductsQuantityUpdateRoute
}

const AuthenticatedAdminProductsRouteRouteChildren: AuthenticatedAdminProductsRouteRouteChildren =
  {
    AuthenticatedAdminProductsAddRoute: AuthenticatedAdminProductsAddRoute,
    AuthenticatedAdminProductsTrashRoute: AuthenticatedAdminProductsTrashRoute,
    AuthenticatedAdminProductsIndexRoute: AuthenticatedAdminProductsIndexRoute,
    AuthenticatedAdminProductsEditIdRoute:
      AuthenticatedAdminProductsEditIdRoute,
    AuthenticatedAdminProductsQuantityUpdateRoute:
      AuthenticatedAdminProductsQuantityUpdateRoute,
  }

const AuthenticatedAdminProductsRouteRouteWithChildren =
  AuthenticatedAdminProductsRouteRoute._addFileChildren(
    AuthenticatedAdminProductsRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminProductsRouteRoute: typeof AuthenticatedAdminProductsRouteRouteWithChildren
  AuthenticatedAdminAboutRoute: typeof AuthenticatedAdminAboutRoute
  AuthenticatedAdminActivityHistoryRoute: typeof AuthenticatedAdminActivityHistoryRoute
  AuthenticatedAdminActivityScheduleRoute: typeof AuthenticatedAdminActivityScheduleRoute
  AuthenticatedAdminCheckPoRoute: typeof AuthenticatedAdminCheckPoRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedEmployeeIndexRoute: typeof AuthenticatedEmployeeIndexRoute
  AuthenticatedAdminAttendancesHistoryRoute: typeof AuthenticatedAdminAttendancesHistoryRoute
  AuthenticatedAdminAttendancesSheetRoute: typeof AuthenticatedAdminAttendancesSheetRoute
  AuthenticatedAdminEmployeesAddRoute: typeof AuthenticatedAdminEmployeesAddRoute
  AuthenticatedAdminPlansMaterialRoute: typeof AuthenticatedAdminPlansMaterialRoute
  AuthenticatedAdminPlansProductionRoute: typeof AuthenticatedAdminPlansProductionRoute
  AuthenticatedAdminStampsBagRoute: typeof AuthenticatedAdminStampsBagRoute
  AuthenticatedAdminStampsBoxRoute: typeof AuthenticatedAdminStampsBoxRoute
  AuthenticatedAdminStampsHistoryRoute: typeof AuthenticatedAdminStampsHistoryRoute
  AuthenticatedAdminStampsRequestRoute: typeof AuthenticatedAdminStampsRequestRoute
  AuthenticatedAdminWorkSchedulesIdRoute: typeof AuthenticatedAdminWorkSchedulesIdRoute
  AuthenticatedAdminSalariesIdLazyRoute: typeof AuthenticatedAdminSalariesIdLazyRoute
  AuthenticatedAdminEmployeesIndexRoute: typeof AuthenticatedAdminEmployeesIndexRoute
  AuthenticatedAdminRolesIndexRoute: typeof AuthenticatedAdminRolesIndexRoute
  AuthenticatedAdminSalariesIndexRoute: typeof AuthenticatedAdminSalariesIndexRoute
  AuthenticatedAdminWorkScheduleCategoriesIndexRoute: typeof AuthenticatedAdminWorkScheduleCategoriesIndexRoute
  AuthenticatedAdminWorkSchedulesIndexRoute: typeof AuthenticatedAdminWorkSchedulesIndexRoute
  AuthenticatedAdminEmployeesEditIdRoute: typeof AuthenticatedAdminEmployeesEditIdRoute
  AuthenticatedAdminEmployeesTrashIndexRoute: typeof AuthenticatedAdminEmployeesTrashIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminProductsRouteRoute:
    AuthenticatedAdminProductsRouteRouteWithChildren,
  AuthenticatedAdminAboutRoute: AuthenticatedAdminAboutRoute,
  AuthenticatedAdminActivityHistoryRoute:
    AuthenticatedAdminActivityHistoryRoute,
  AuthenticatedAdminActivityScheduleRoute:
    AuthenticatedAdminActivityScheduleRoute,
  AuthenticatedAdminCheckPoRoute: AuthenticatedAdminCheckPoRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedEmployeeIndexRoute: AuthenticatedEmployeeIndexRoute,
  AuthenticatedAdminAttendancesHistoryRoute:
    AuthenticatedAdminAttendancesHistoryRoute,
  AuthenticatedAdminAttendancesSheetRoute:
    AuthenticatedAdminAttendancesSheetRoute,
  AuthenticatedAdminEmployeesAddRoute: AuthenticatedAdminEmployeesAddRoute,
  AuthenticatedAdminPlansMaterialRoute: AuthenticatedAdminPlansMaterialRoute,
  AuthenticatedAdminPlansProductionRoute:
    AuthenticatedAdminPlansProductionRoute,
  AuthenticatedAdminStampsBagRoute: AuthenticatedAdminStampsBagRoute,
  AuthenticatedAdminStampsBoxRoute: AuthenticatedAdminStampsBoxRoute,
  AuthenticatedAdminStampsHistoryRoute: AuthenticatedAdminStampsHistoryRoute,
  AuthenticatedAdminStampsRequestRoute: AuthenticatedAdminStampsRequestRoute,
  AuthenticatedAdminWorkSchedulesIdRoute:
    AuthenticatedAdminWorkSchedulesIdRoute,
  AuthenticatedAdminSalariesIdLazyRoute: AuthenticatedAdminSalariesIdLazyRoute,
  AuthenticatedAdminEmployeesIndexRoute: AuthenticatedAdminEmployeesIndexRoute,
  AuthenticatedAdminRolesIndexRoute: AuthenticatedAdminRolesIndexRoute,
  AuthenticatedAdminSalariesIndexRoute: AuthenticatedAdminSalariesIndexRoute,
  AuthenticatedAdminWorkScheduleCategoriesIndexRoute:
    AuthenticatedAdminWorkScheduleCategoriesIndexRoute,
  AuthenticatedAdminWorkSchedulesIndexRoute:
    AuthenticatedAdminWorkSchedulesIndexRoute,
  AuthenticatedAdminEmployeesEditIdRoute:
    AuthenticatedAdminEmployeesEditIdRoute,
  AuthenticatedAdminEmployeesTrashIndexRoute:
    AuthenticatedAdminEmployeesTrashIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/login': typeof authLoginRoute
  '/admin/products': typeof AuthenticatedAdminProductsRouteRouteWithChildren
  '/admin/about': typeof AuthenticatedAdminAboutRoute
  '/admin/activity-history': typeof AuthenticatedAdminActivityHistoryRoute
  '/admin/activity-schedule': typeof AuthenticatedAdminActivityScheduleRoute
  '/admin/check-po': typeof AuthenticatedAdminCheckPoRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/employee': typeof AuthenticatedEmployeeIndexRoute
  '/admin/attendances/history': typeof AuthenticatedAdminAttendancesHistoryRoute
  '/admin/attendances/sheet': typeof AuthenticatedAdminAttendancesSheetRoute
  '/admin/employees/add': typeof AuthenticatedAdminEmployeesAddRoute
  '/admin/plans/material': typeof AuthenticatedAdminPlansMaterialRoute
  '/admin/plans/production': typeof AuthenticatedAdminPlansProductionRoute
  '/admin/products/add': typeof AuthenticatedAdminProductsAddRoute
  '/admin/products/trash': typeof AuthenticatedAdminProductsTrashRoute
  '/admin/stamps/bag': typeof AuthenticatedAdminStampsBagRoute
  '/admin/stamps/box': typeof AuthenticatedAdminStampsBoxRoute
  '/admin/stamps/history': typeof AuthenticatedAdminStampsHistoryRoute
  '/admin/stamps/request': typeof AuthenticatedAdminStampsRequestRoute
  '/admin/work-schedules/$id': typeof AuthenticatedAdminWorkSchedulesIdRoute
  '/admin/salaries/$id': typeof AuthenticatedAdminSalariesIdLazyRoute
  '/admin/employees': typeof AuthenticatedAdminEmployeesIndexRoute
  '/admin/products/': typeof AuthenticatedAdminProductsIndexRoute
  '/admin/roles': typeof AuthenticatedAdminRolesIndexRoute
  '/admin/salaries': typeof AuthenticatedAdminSalariesIndexRoute
  '/admin/work-schedule-categories': typeof AuthenticatedAdminWorkScheduleCategoriesIndexRoute
  '/admin/work-schedules': typeof AuthenticatedAdminWorkSchedulesIndexRoute
  '/admin/employees/edit/$id': typeof AuthenticatedAdminEmployeesEditIdRoute
  '/admin/products/edit/$id': typeof AuthenticatedAdminProductsEditIdRoute
  '/admin/products/quantity/update': typeof AuthenticatedAdminProductsQuantityUpdateRoute
  '/admin/employees/trash': typeof AuthenticatedAdminEmployeesTrashIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof authLoginRoute
  '/admin/about': typeof AuthenticatedAdminAboutRoute
  '/admin/activity-history': typeof AuthenticatedAdminActivityHistoryRoute
  '/admin/activity-schedule': typeof AuthenticatedAdminActivityScheduleRoute
  '/admin/check-po': typeof AuthenticatedAdminCheckPoRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/employee': typeof AuthenticatedEmployeeIndexRoute
  '/admin/attendances/history': typeof AuthenticatedAdminAttendancesHistoryRoute
  '/admin/attendances/sheet': typeof AuthenticatedAdminAttendancesSheetRoute
  '/admin/employees/add': typeof AuthenticatedAdminEmployeesAddRoute
  '/admin/plans/material': typeof AuthenticatedAdminPlansMaterialRoute
  '/admin/plans/production': typeof AuthenticatedAdminPlansProductionRoute
  '/admin/products/add': typeof AuthenticatedAdminProductsAddRoute
  '/admin/products/trash': typeof AuthenticatedAdminProductsTrashRoute
  '/admin/stamps/bag': typeof AuthenticatedAdminStampsBagRoute
  '/admin/stamps/box': typeof AuthenticatedAdminStampsBoxRoute
  '/admin/stamps/history': typeof AuthenticatedAdminStampsHistoryRoute
  '/admin/stamps/request': typeof AuthenticatedAdminStampsRequestRoute
  '/admin/work-schedules/$id': typeof AuthenticatedAdminWorkSchedulesIdRoute
  '/admin/salaries/$id': typeof AuthenticatedAdminSalariesIdLazyRoute
  '/admin/employees': typeof AuthenticatedAdminEmployeesIndexRoute
  '/admin/products': typeof AuthenticatedAdminProductsIndexRoute
  '/admin/roles': typeof AuthenticatedAdminRolesIndexRoute
  '/admin/salaries': typeof AuthenticatedAdminSalariesIndexRoute
  '/admin/work-schedule-categories': typeof AuthenticatedAdminWorkScheduleCategoriesIndexRoute
  '/admin/work-schedules': typeof AuthenticatedAdminWorkSchedulesIndexRoute
  '/admin/employees/edit/$id': typeof AuthenticatedAdminEmployeesEditIdRoute
  '/admin/products/edit/$id': typeof AuthenticatedAdminProductsEditIdRoute
  '/admin/products/quantity/update': typeof AuthenticatedAdminProductsQuantityUpdateRoute
  '/admin/employees/trash': typeof AuthenticatedAdminEmployeesTrashIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRouteRouteWithChildren
  '/_authenticated/admin/about': typeof AuthenticatedAdminAboutRoute
  '/_authenticated/admin/activity-history': typeof AuthenticatedAdminActivityHistoryRoute
  '/_authenticated/admin/activity-schedule': typeof AuthenticatedAdminActivityScheduleRoute
  '/_authenticated/admin/check-po': typeof AuthenticatedAdminCheckPoRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/employee/': typeof AuthenticatedEmployeeIndexRoute
  '/_authenticated/admin/attendances/history': typeof AuthenticatedAdminAttendancesHistoryRoute
  '/_authenticated/admin/attendances/sheet': typeof AuthenticatedAdminAttendancesSheetRoute
  '/_authenticated/admin/employees/add': typeof AuthenticatedAdminEmployeesAddRoute
  '/_authenticated/admin/plans/material': typeof AuthenticatedAdminPlansMaterialRoute
  '/_authenticated/admin/plans/production': typeof AuthenticatedAdminPlansProductionRoute
  '/_authenticated/admin/products/add': typeof AuthenticatedAdminProductsAddRoute
  '/_authenticated/admin/products/trash': typeof AuthenticatedAdminProductsTrashRoute
  '/_authenticated/admin/stamps/bag': typeof AuthenticatedAdminStampsBagRoute
  '/_authenticated/admin/stamps/box': typeof AuthenticatedAdminStampsBoxRoute
  '/_authenticated/admin/stamps/history': typeof AuthenticatedAdminStampsHistoryRoute
  '/_authenticated/admin/stamps/request': typeof AuthenticatedAdminStampsRequestRoute
  '/_authenticated/admin/work-schedules/$id': typeof AuthenticatedAdminWorkSchedulesIdRoute
  '/_authenticated/admin/salaries/$id': typeof AuthenticatedAdminSalariesIdLazyRoute
  '/_authenticated/admin/employees/': typeof AuthenticatedAdminEmployeesIndexRoute
  '/_authenticated/admin/products/': typeof AuthenticatedAdminProductsIndexRoute
  '/_authenticated/admin/roles/': typeof AuthenticatedAdminRolesIndexRoute
  '/_authenticated/admin/salaries/': typeof AuthenticatedAdminSalariesIndexRoute
  '/_authenticated/admin/work-schedule-categories/': typeof AuthenticatedAdminWorkScheduleCategoriesIndexRoute
  '/_authenticated/admin/work-schedules/': typeof AuthenticatedAdminWorkSchedulesIndexRoute
  '/_authenticated/admin/employees/edit/$id': typeof AuthenticatedAdminEmployeesEditIdRoute
  '/_authenticated/admin/products/edit/$id': typeof AuthenticatedAdminProductsEditIdRoute
  '/_authenticated/admin/products/quantity/update': typeof AuthenticatedAdminProductsQuantityUpdateRoute
  '/_authenticated/admin/employees/trash/': typeof AuthenticatedAdminEmployeesTrashIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/admin/products'
    | '/admin/about'
    | '/admin/activity-history'
    | '/admin/activity-schedule'
    | '/admin/check-po'
    | '/admin'
    | '/employee'
    | '/admin/attendances/history'
    | '/admin/attendances/sheet'
    | '/admin/employees/add'
    | '/admin/plans/material'
    | '/admin/plans/production'
    | '/admin/products/add'
    | '/admin/products/trash'
    | '/admin/stamps/bag'
    | '/admin/stamps/box'
    | '/admin/stamps/history'
    | '/admin/stamps/request'
    | '/admin/work-schedules/$id'
    | '/admin/salaries/$id'
    | '/admin/employees'
    | '/admin/products/'
    | '/admin/roles'
    | '/admin/salaries'
    | '/admin/work-schedule-categories'
    | '/admin/work-schedules'
    | '/admin/employees/edit/$id'
    | '/admin/products/edit/$id'
    | '/admin/products/quantity/update'
    | '/admin/employees/trash'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/about'
    | '/admin/activity-history'
    | '/admin/activity-schedule'
    | '/admin/check-po'
    | '/admin'
    | '/employee'
    | '/admin/attendances/history'
    | '/admin/attendances/sheet'
    | '/admin/employees/add'
    | '/admin/plans/material'
    | '/admin/plans/production'
    | '/admin/products/add'
    | '/admin/products/trash'
    | '/admin/stamps/bag'
    | '/admin/stamps/box'
    | '/admin/stamps/history'
    | '/admin/stamps/request'
    | '/admin/work-schedules/$id'
    | '/admin/salaries/$id'
    | '/admin/employees'
    | '/admin/products'
    | '/admin/roles'
    | '/admin/salaries'
    | '/admin/work-schedule-categories'
    | '/admin/work-schedules'
    | '/admin/employees/edit/$id'
    | '/admin/products/edit/$id'
    | '/admin/products/quantity/update'
    | '/admin/employees/trash'
  id:
    | '__root__'
    | '/(auth)'
    | '/_authenticated'
    | '/(auth)/login'
    | '/_authenticated/'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/about'
    | '/_authenticated/admin/activity-history'
    | '/_authenticated/admin/activity-schedule'
    | '/_authenticated/admin/check-po'
    | '/_authenticated/admin/'
    | '/_authenticated/employee/'
    | '/_authenticated/admin/attendances/history'
    | '/_authenticated/admin/attendances/sheet'
    | '/_authenticated/admin/employees/add'
    | '/_authenticated/admin/plans/material'
    | '/_authenticated/admin/plans/production'
    | '/_authenticated/admin/products/add'
    | '/_authenticated/admin/products/trash'
    | '/_authenticated/admin/stamps/bag'
    | '/_authenticated/admin/stamps/box'
    | '/_authenticated/admin/stamps/history'
    | '/_authenticated/admin/stamps/request'
    | '/_authenticated/admin/work-schedules/$id'
    | '/_authenticated/admin/salaries/$id'
    | '/_authenticated/admin/employees/'
    | '/_authenticated/admin/products/'
    | '/_authenticated/admin/roles/'
    | '/_authenticated/admin/salaries/'
    | '/_authenticated/admin/work-schedule-categories/'
    | '/_authenticated/admin/work-schedules/'
    | '/_authenticated/admin/employees/edit/$id'
    | '/_authenticated/admin/products/edit/$id'
    | '/_authenticated/admin/products/quantity/update'
    | '/_authenticated/admin/employees/trash/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(auth)",
        "/_authenticated"
      ]
    },
    "/(auth)": {
      "filePath": "(auth)/route.tsx",
      "children": [
        "/(auth)/login"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/",
        "/_authenticated/admin/products",
        "/_authenticated/admin/about",
        "/_authenticated/admin/activity-history",
        "/_authenticated/admin/activity-schedule",
        "/_authenticated/admin/check-po",
        "/_authenticated/admin/",
        "/_authenticated/employee/",
        "/_authenticated/admin/attendances/history",
        "/_authenticated/admin/attendances/sheet",
        "/_authenticated/admin/employees/add",
        "/_authenticated/admin/plans/material",
        "/_authenticated/admin/plans/production",
        "/_authenticated/admin/stamps/bag",
        "/_authenticated/admin/stamps/box",
        "/_authenticated/admin/stamps/history",
        "/_authenticated/admin/stamps/request",
        "/_authenticated/admin/work-schedules/$id",
        "/_authenticated/admin/salaries/$id",
        "/_authenticated/admin/employees/",
        "/_authenticated/admin/roles/",
        "/_authenticated/admin/salaries/",
        "/_authenticated/admin/work-schedule-categories/",
        "/_authenticated/admin/work-schedules/",
        "/_authenticated/admin/employees/edit/$id",
        "/_authenticated/admin/employees/trash/"
      ]
    },
    "/(auth)/login": {
      "filePath": "(auth)/login.tsx",
      "parent": "/(auth)"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/products": {
      "filePath": "_authenticated/admin/products/route.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/admin/products/add",
        "/_authenticated/admin/products/trash",
        "/_authenticated/admin/products/",
        "/_authenticated/admin/products/edit/$id",
        "/_authenticated/admin/products/quantity/update"
      ]
    },
    "/_authenticated/admin/about": {
      "filePath": "_authenticated/admin/about.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/activity-history": {
      "filePath": "_authenticated/admin/activity-history.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/activity-schedule": {
      "filePath": "_authenticated/admin/activity-schedule.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/check-po": {
      "filePath": "_authenticated/admin/check-po.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/": {
      "filePath": "_authenticated/admin/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/employee/": {
      "filePath": "_authenticated/employee/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/attendances/history": {
      "filePath": "_authenticated/admin/attendances/history.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/attendances/sheet": {
      "filePath": "_authenticated/admin/attendances/sheet.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/employees/add": {
      "filePath": "_authenticated/admin/employees/add.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/plans/material": {
      "filePath": "_authenticated/admin/plans/material.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/plans/production": {
      "filePath": "_authenticated/admin/plans/production.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/products/add": {
      "filePath": "_authenticated/admin/products/add.tsx",
      "parent": "/_authenticated/admin/products"
    },
    "/_authenticated/admin/products/trash": {
      "filePath": "_authenticated/admin/products/trash.tsx",
      "parent": "/_authenticated/admin/products"
    },
    "/_authenticated/admin/stamps/bag": {
      "filePath": "_authenticated/admin/stamps/bag.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/stamps/box": {
      "filePath": "_authenticated/admin/stamps/box.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/stamps/history": {
      "filePath": "_authenticated/admin/stamps/history.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/stamps/request": {
      "filePath": "_authenticated/admin/stamps/request.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/work-schedules/$id": {
      "filePath": "_authenticated/admin/work-schedules/$id.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/salaries/$id": {
      "filePath": "_authenticated/admin/salaries/$id.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/employees/": {
      "filePath": "_authenticated/admin/employees/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/products/": {
      "filePath": "_authenticated/admin/products/index.tsx",
      "parent": "/_authenticated/admin/products"
    },
    "/_authenticated/admin/roles/": {
      "filePath": "_authenticated/admin/roles/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/salaries/": {
      "filePath": "_authenticated/admin/salaries/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/work-schedule-categories/": {
      "filePath": "_authenticated/admin/work-schedule-categories/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/work-schedules/": {
      "filePath": "_authenticated/admin/work-schedules/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/employees/edit/$id": {
      "filePath": "_authenticated/admin/employees/edit.$id.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/products/edit/$id": {
      "filePath": "_authenticated/admin/products/edit.$id.tsx",
      "parent": "/_authenticated/admin/products"
    },
    "/_authenticated/admin/products/quantity/update": {
      "filePath": "_authenticated/admin/products/quantity/update.tsx",
      "parent": "/_authenticated/admin/products"
    },
    "/_authenticated/admin/employees/trash/": {
      "filePath": "_authenticated/admin/employees/trash/index.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
