/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ForbiddenImport } from './routes/forbidden'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as authRouteImport } from './routes/(auth)/route'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as authLoginImport } from './routes/(auth)/login'
import { Route as AuthenticatedWorkSchedulesRouteImport } from './routes/_authenticated/work-schedules/route'
import { Route as AuthenticatedStampsRouteImport } from './routes/_authenticated/stamps/route'
import { Route as AuthenticatedEmployeeRouteImport } from './routes/_authenticated/employee/route'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedActivityScheduleRouteImport } from './routes/_authenticated/activity-schedule/route'
import { Route as AuthenticatedWorkSchedulesIndexImport } from './routes/_authenticated/work-schedules/index'
import { Route as AuthenticatedScanIndexImport } from './routes/_authenticated/scan/index'
import { Route as AuthenticatedRequestFormsIndexImport } from './routes/_authenticated/request-forms/index'
import { Route as AuthenticatedProfileIndexImport } from './routes/_authenticated/profile/index'
import { Route as AuthenticatedActivityScheduleIndexImport } from './routes/_authenticated/activity-schedule/index'
import { Route as AuthenticatedWorkSchedulesIdImport } from './routes/_authenticated/work-schedules/$id'
import { Route as AuthenticatedStampsHistoryImport } from './routes/_authenticated/stamps/history'
import { Route as AuthenticatedStampsCreateImport } from './routes/_authenticated/stamps/create'
import { Route as AuthenticatedScanStorageImport } from './routes/_authenticated/scan/storage'
import { Route as AuthenticatedRequestFormsIdImport } from './routes/_authenticated/request-forms/$id'
import { Route as AuthenticatedAdminNotificationDemoImport } from './routes/_authenticated/admin/notification-demo'
import { Route as AuthenticatedAdminAboutImport } from './routes/_authenticated/admin/about'
import { Route as AuthenticatedEmployeeRequestFormsRouteImport } from './routes/_authenticated/employee/request-forms/route'
import { Route as AuthenticatedAdminSalariesRouteImport } from './routes/_authenticated/admin/salaries/route'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin/products/route'
import { Route as AuthenticatedEmployeeSchedulesIndexImport } from './routes/_authenticated/employee/schedules/index'
import { Route as AuthenticatedEmployeeSalariesIndexImport } from './routes/_authenticated/employee/salaries/index'
import { Route as AuthenticatedEmployeeRequestFormsIndexImport } from './routes/_authenticated/employee/request-forms/index'
import { Route as AuthenticatedEmployeeActivityScheduleIndexImport } from './routes/_authenticated/employee/activity-schedule/index'
import { Route as AuthenticatedAdminWorkScheduleCategoriesIndexImport } from './routes/_authenticated/admin/work-schedule-categories/index'
import { Route as AuthenticatedAdminSalariesIndexImport } from './routes/_authenticated/admin/salaries/index'
import { Route as AuthenticatedAdminRolesIndexImport } from './routes/_authenticated/admin/roles/index'
import { Route as AuthenticatedAdminProductsIndexImport } from './routes/_authenticated/admin/products/index'
import { Route as AuthenticatedAdminHistoryIndexImport } from './routes/_authenticated/admin/history/index'
import { Route as AuthenticatedAdminEmployeesIndexImport } from './routes/_authenticated/admin/employees/index'
import { Route as AuthenticatedAdminEditLayoutIndexImport } from './routes/_authenticated/admin/edit-layout/index'
import { Route as AuthenticatedAdminCheckPoIndexImport } from './routes/_authenticated/admin/check-po/index'
import { Route as AuthenticatedEmployeeTodoUpdateQuantityErrorImport } from './routes/_authenticated/employee/todo/update-quantity-error'
import { Route as AuthenticatedEmployeeTodoUpdateQuantityImport } from './routes/_authenticated/employee/todo/update-quantity'
import { Route as AuthenticatedEmployeeTodoHistoryImport } from './routes/_authenticated/employee/todo/history'
import { Route as AuthenticatedEmployeeTodoAddProductImport } from './routes/_authenticated/employee/todo/add-product'
import { Route as AuthenticatedEmployeeStampsRequestImport } from './routes/_authenticated/employee/stamps/request'
import { Route as AuthenticatedEmployeeStampsHistoryImport } from './routes/_authenticated/employee/stamps/history'
import { Route as AuthenticatedEmployeeSchedulesIdImport } from './routes/_authenticated/employee/schedules/$id'
import { Route as AuthenticatedEmployeeSalariesIdImport } from './routes/_authenticated/employee/salaries/$id'
import { Route as AuthenticatedEmployeeRequestFormsAuthorizedImport } from './routes/_authenticated/employee/request-forms/authorized'
import { Route as AuthenticatedAdminProductsTrashImport } from './routes/_authenticated/admin/products/trash'
import { Route as AuthenticatedAdminProductsAddImport } from './routes/_authenticated/admin/products/add'
import { Route as AuthenticatedAdminProductsIdImport } from './routes/_authenticated/admin/products/$id'
import { Route as AuthenticatedAdminPlansProductionImport } from './routes/_authenticated/admin/plans/production'
import { Route as AuthenticatedAdminPlansMaterialImport } from './routes/_authenticated/admin/plans/material'
import { Route as AuthenticatedAdminEmployeesAddImport } from './routes/_authenticated/admin/employees/add'
import { Route as AuthenticatedAdminCheckPoHistoryImport } from './routes/_authenticated/admin/check-po/history'
import { Route as AuthenticatedAdminCheckPoAddInventoryImport } from './routes/_authenticated/admin/check-po/add-inventory'
import { Route as AuthenticatedAdminCheckPoAddExportImport } from './routes/_authenticated/admin/check-po/add-export'
import { Route as AuthenticatedAdminCheckPoAddImport } from './routes/_authenticated/admin/check-po/add'
import { Route as AuthenticatedAdminAttendancesRecordImport } from './routes/_authenticated/admin/attendances/record'
import { Route as AuthenticatedAdminAttendancesHistoryImport } from './routes/_authenticated/admin/attendances/history'
import { Route as AuthenticatedEmployeeAttendancesHistoryIndexImport } from './routes/_authenticated/employee/attendances/history/index'
import { Route as AuthenticatedEmployeeAttendancesCalculateIndexImport } from './routes/_authenticated/employee/attendances/calculate/index'
import { Route as AuthenticatedAdminEmployeesTrashIndexImport } from './routes/_authenticated/admin/employees/trash/index'
import { Route as AuthenticatedAdminProductsQuantityUpdateImport } from './routes/_authenticated/admin/products/quantity/update'
import { Route as AuthenticatedAdminProductsQuantityAddImport } from './routes/_authenticated/admin/products/quantity/add'
import { Route as AuthenticatedAdminProductsEditIdImport } from './routes/_authenticated/admin/products/edit.$id'
import { Route as AuthenticatedAdminEmployeesEditIdImport } from './routes/_authenticated/admin/employees/edit.$id'

// Create Virtual Routes

const AuthenticatedAdminSalariesIdLazyImport = createFileRoute(
  '/_authenticated/admin/salaries/$id',
)()

// Create/Update Routes

const ForbiddenRoute = ForbiddenImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const authRouteRoute = authRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const authLoginRoute = authLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)

const AuthenticatedWorkSchedulesRouteRoute =
  AuthenticatedWorkSchedulesRouteImport.update({
    id: '/work-schedules',
    path: '/work-schedules',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedStampsRouteRoute = AuthenticatedStampsRouteImport.update({
  id: '/stamps',
  path: '/stamps',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedEmployeeRouteRoute = AuthenticatedEmployeeRouteImport.update(
  {
    id: '/employee',
    path: '/employee',
    getParentRoute: () => AuthenticatedRoute,
  } as any,
)

const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedActivityScheduleRouteRoute =
  AuthenticatedActivityScheduleRouteImport.update({
    id: '/activity-schedule',
    path: '/activity-schedule',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedWorkSchedulesIndexRoute =
  AuthenticatedWorkSchedulesIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkSchedulesRouteRoute,
  } as any)

const AuthenticatedScanIndexRoute = AuthenticatedScanIndexImport.update({
  id: '/scan/',
  path: '/scan/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedRequestFormsIndexRoute =
  AuthenticatedRequestFormsIndexImport.update({
    id: '/request-forms/',
    path: '/request-forms/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedProfileIndexRoute = AuthenticatedProfileIndexImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedActivityScheduleIndexRoute =
  AuthenticatedActivityScheduleIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedActivityScheduleRouteRoute,
  } as any)

const AuthenticatedWorkSchedulesIdRoute =
  AuthenticatedWorkSchedulesIdImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedWorkSchedulesRouteRoute,
  } as any)

const AuthenticatedStampsHistoryRoute = AuthenticatedStampsHistoryImport.update(
  {
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedStampsRouteRoute,
  } as any,
)

const AuthenticatedStampsCreateRoute = AuthenticatedStampsCreateImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthenticatedStampsRouteRoute,
} as any)

const AuthenticatedScanStorageRoute = AuthenticatedScanStorageImport.update({
  id: '/scan/storage',
  path: '/scan/storage',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedRequestFormsIdRoute =
  AuthenticatedRequestFormsIdImport.update({
    id: '/request-forms/$id',
    path: '/request-forms/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedAdminNotificationDemoRoute =
  AuthenticatedAdminNotificationDemoImport.update({
    id: '/notification-demo',
    path: '/notification-demo',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

const AuthenticatedAdminAboutRoute = AuthenticatedAdminAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)

const AuthenticatedEmployeeRequestFormsRouteRoute =
  AuthenticatedEmployeeRequestFormsRouteImport.update({
    id: '/request-forms',
    path: '/request-forms',
    getParentRoute: () => AuthenticatedEmployeeRouteRoute,
  } as any)

const AuthenticatedAdminSalariesRouteRoute =
  AuthenticatedAdminSalariesRouteImport.update({
    id: '/salaries',
    path: '/salaries',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

const AuthenticatedAdminProductsRouteRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

const AuthenticatedEmployeeSchedulesIndexRoute =
  AuthenticatedEmployeeSchedulesIndexImport.update({
    id: '/schedules/',
    path: '/schedules/',
    getParentRoute: () => AuthenticatedEmployeeRouteRoute,
  } as any)

const AuthenticatedEmployeeSalariesIndexRoute =
  AuthenticatedEmployeeSalariesIndexImport.update({
    id: '/salaries/',
    path: '/salaries/',
    getParentRoute: () => AuthenticatedEmployeeRouteRoute,
  } as any)

const AuthenticatedEmployeeRequestFormsIndexRoute =
  AuthenticatedEmployeeRequestFormsIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEmployeeRequestFormsRouteRoute,
  } as any)

const AuthenticatedEmployeeActivityScheduleIndexRoute =
  AuthenticatedEmployeeActivityScheduleIndexImport.update({
    id: '/activity-schedule/',
    path: '/activity-schedule/',
    getParentRoute: () => AuthenticatedEmployeeRouteRoute,
  } as any)

const AuthenticatedAdminWorkScheduleCategoriesIndexRoute =
  AuthenticatedAdminWorkScheduleCategoriesIndexImport.update({
    id: '/work-schedule-categories/',
    path: '/work-schedule-categories/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

const AuthenticatedAdminSalariesIndexRoute =
  AuthenticatedAdminSalariesIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminSalariesRouteRoute,
  } as any)

const AuthenticatedAdminRolesIndexRoute =
  AuthenticatedAdminRolesIndexImport.update({
    id: '/roles/',
    path: '/roles/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

const AuthenticatedAdminProductsIndexRoute =
  AuthenticatedAdminProductsIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminProductsRouteRoute,
  } as any)

const AuthenticatedAdminHistoryIndexRoute =
  AuthenticatedAdminHistoryIndexImport.update({
    id: '/history/',
    path: '/history/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

const AuthenticatedAdminEmployeesIndexRoute =
  AuthenticatedAdminEmployeesIndexImport.update({
    id: '/employees/',
    path: '/employees/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

const AuthenticatedAdminEditLayoutIndexRoute =
  AuthenticatedAdminEditLayoutIndexImport.update({
    id: '/edit-layout/',
    path: '/edit-layout/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

const AuthenticatedAdminCheckPoIndexRoute =
  AuthenticatedAdminCheckPoIndexImport.update({
    id: '/check-po/',
    path: '/check-po/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

const AuthenticatedAdminSalariesIdLazyRoute =
  AuthenticatedAdminSalariesIdLazyImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminSalariesRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/admin/salaries/$id.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedEmployeeTodoUpdateQuantityErrorRoute =
  AuthenticatedEmployeeTodoUpdateQuantityErrorImport.update({
    id: '/todo/update-quantity-error',
    path: '/todo/update-quantity-error',
    getParentRoute: () => AuthenticatedEmployeeRouteRoute,
  } as any)

const AuthenticatedEmployeeTodoUpdateQuantityRoute =
  AuthenticatedEmployeeTodoUpdateQuantityImport.update({
    id: '/todo/update-quantity',
    path: '/todo/update-quantity',
    getParentRoute: () => AuthenticatedEmployeeRouteRoute,
  } as any)

const AuthenticatedEmployeeTodoHistoryRoute =
  AuthenticatedEmployeeTodoHistoryImport.update({
    id: '/todo/history',
    path: '/todo/history',
    getParentRoute: () => AuthenticatedEmployeeRouteRoute,
  } as any)

const AuthenticatedEmployeeTodoAddProductRoute =
  AuthenticatedEmployeeTodoAddProductImport.update({
    id: '/todo/add-product',
    path: '/todo/add-product',
    getParentRoute: () => AuthenticatedEmployeeRouteRoute,
  } as any)

const AuthenticatedEmployeeStampsRequestRoute =
  AuthenticatedEmployeeStampsRequestImport.update({
    id: '/stamps/request',
    path: '/stamps/request',
    getParentRoute: () => AuthenticatedEmployeeRouteRoute,
  } as any)

const AuthenticatedEmployeeStampsHistoryRoute =
  AuthenticatedEmployeeStampsHistoryImport.update({
    id: '/stamps/history',
    path: '/stamps/history',
    getParentRoute: () => AuthenticatedEmployeeRouteRoute,
  } as any)

const AuthenticatedEmployeeSchedulesIdRoute =
  AuthenticatedEmployeeSchedulesIdImport.update({
    id: '/schedules/$id',
    path: '/schedules/$id',
    getParentRoute: () => AuthenticatedEmployeeRouteRoute,
  } as any)

const AuthenticatedEmployeeSalariesIdRoute =
  AuthenticatedEmployeeSalariesIdImport.update({
    id: '/salaries/$id',
    path: '/salaries/$id',
    getParentRoute: () => AuthenticatedEmployeeRouteRoute,
  } as any)

const AuthenticatedEmployeeRequestFormsAuthorizedRoute =
  AuthenticatedEmployeeRequestFormsAuthorizedImport.update({
    id: '/authorized',
    path: '/authorized',
    getParentRoute: () => AuthenticatedEmployeeRequestFormsRouteRoute,
  } as any)

const AuthenticatedAdminProductsTrashRoute =
  AuthenticatedAdminProductsTrashImport.update({
    id: '/trash',
    path: '/trash',
    getParentRoute: () => AuthenticatedAdminProductsRouteRoute,
  } as any)

const AuthenticatedAdminProductsAddRoute =
  AuthenticatedAdminProductsAddImport.update({
    id: '/add',
    path: '/add',
    getParentRoute: () => AuthenticatedAdminProductsRouteRoute,
  } as any)

const AuthenticatedAdminProductsIdRoute =
  AuthenticatedAdminProductsIdImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminProductsRouteRoute,
  } as any)

const AuthenticatedAdminPlansProductionRoute =
  AuthenticatedAdminPlansProductionImport.update({
    id: '/plans/production',
    path: '/plans/production',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

const AuthenticatedAdminPlansMaterialRoute =
  AuthenticatedAdminPlansMaterialImport.update({
    id: '/plans/material',
    path: '/plans/material',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

const AuthenticatedAdminEmployeesAddRoute =
  AuthenticatedAdminEmployeesAddImport.update({
    id: '/employees/add',
    path: '/employees/add',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

const AuthenticatedAdminCheckPoHistoryRoute =
  AuthenticatedAdminCheckPoHistoryImport.update({
    id: '/check-po/history',
    path: '/check-po/history',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

const AuthenticatedAdminCheckPoAddInventoryRoute =
  AuthenticatedAdminCheckPoAddInventoryImport.update({
    id: '/check-po/add-inventory',
    path: '/check-po/add-inventory',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

const AuthenticatedAdminCheckPoAddExportRoute =
  AuthenticatedAdminCheckPoAddExportImport.update({
    id: '/check-po/add-export',
    path: '/check-po/add-export',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

const AuthenticatedAdminCheckPoAddRoute =
  AuthenticatedAdminCheckPoAddImport.update({
    id: '/check-po/add',
    path: '/check-po/add',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

const AuthenticatedAdminAttendancesRecordRoute =
  AuthenticatedAdminAttendancesRecordImport.update({
    id: '/attendances/record',
    path: '/attendances/record',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

const AuthenticatedAdminAttendancesHistoryRoute =
  AuthenticatedAdminAttendancesHistoryImport.update({
    id: '/attendances/history',
    path: '/attendances/history',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

const AuthenticatedEmployeeAttendancesHistoryIndexRoute =
  AuthenticatedEmployeeAttendancesHistoryIndexImport.update({
    id: '/attendances/history/',
    path: '/attendances/history/',
    getParentRoute: () => AuthenticatedEmployeeRouteRoute,
  } as any)

const AuthenticatedEmployeeAttendancesCalculateIndexRoute =
  AuthenticatedEmployeeAttendancesCalculateIndexImport.update({
    id: '/attendances/calculate/',
    path: '/attendances/calculate/',
    getParentRoute: () => AuthenticatedEmployeeRouteRoute,
  } as any)

const AuthenticatedAdminEmployeesTrashIndexRoute =
  AuthenticatedAdminEmployeesTrashIndexImport.update({
    id: '/employees/trash/',
    path: '/employees/trash/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

const AuthenticatedAdminProductsQuantityUpdateRoute =
  AuthenticatedAdminProductsQuantityUpdateImport.update({
    id: '/quantity/update',
    path: '/quantity/update',
    getParentRoute: () => AuthenticatedAdminProductsRouteRoute,
  } as any)

const AuthenticatedAdminProductsQuantityAddRoute =
  AuthenticatedAdminProductsQuantityAddImport.update({
    id: '/quantity/add',
    path: '/quantity/add',
    getParentRoute: () => AuthenticatedAdminProductsRouteRoute,
  } as any)

const AuthenticatedAdminProductsEditIdRoute =
  AuthenticatedAdminProductsEditIdImport.update({
    id: '/edit/$id',
    path: '/edit/$id',
    getParentRoute: () => AuthenticatedAdminProductsRouteRoute,
  } as any)

const AuthenticatedAdminEmployeesEditIdRoute =
  AuthenticatedAdminEmployeesEditIdImport.update({
    id: '/employees/edit/$id',
    path: '/employees/edit/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authRouteImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/activity-schedule': {
      id: '/_authenticated/activity-schedule'
      path: '/activity-schedule'
      fullPath: '/activity-schedule'
      preLoaderRoute: typeof AuthenticatedActivityScheduleRouteImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/employee': {
      id: '/_authenticated/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof AuthenticatedEmployeeRouteImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/stamps': {
      id: '/_authenticated/stamps'
      path: '/stamps'
      fullPath: '/stamps'
      preLoaderRoute: typeof AuthenticatedStampsRouteImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/work-schedules': {
      id: '/_authenticated/work-schedules'
      path: '/work-schedules'
      fullPath: '/work-schedules'
      preLoaderRoute: typeof AuthenticatedWorkSchedulesRouteImport
      parentRoute: typeof AuthenticatedImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginImport
      parentRoute: typeof authRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/admin/salaries': {
      id: '/_authenticated/admin/salaries'
      path: '/salaries'
      fullPath: '/admin/salaries'
      preLoaderRoute: typeof AuthenticatedAdminSalariesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/employee/request-forms': {
      id: '/_authenticated/employee/request-forms'
      path: '/request-forms'
      fullPath: '/employee/request-forms'
      preLoaderRoute: typeof AuthenticatedEmployeeRequestFormsRouteImport
      parentRoute: typeof AuthenticatedEmployeeRouteImport
    }
    '/_authenticated/admin/about': {
      id: '/_authenticated/admin/about'
      path: '/about'
      fullPath: '/admin/about'
      preLoaderRoute: typeof AuthenticatedAdminAboutImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/admin/notification-demo': {
      id: '/_authenticated/admin/notification-demo'
      path: '/notification-demo'
      fullPath: '/admin/notification-demo'
      preLoaderRoute: typeof AuthenticatedAdminNotificationDemoImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/request-forms/$id': {
      id: '/_authenticated/request-forms/$id'
      path: '/request-forms/$id'
      fullPath: '/request-forms/$id'
      preLoaderRoute: typeof AuthenticatedRequestFormsIdImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/scan/storage': {
      id: '/_authenticated/scan/storage'
      path: '/scan/storage'
      fullPath: '/scan/storage'
      preLoaderRoute: typeof AuthenticatedScanStorageImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/stamps/create': {
      id: '/_authenticated/stamps/create'
      path: '/create'
      fullPath: '/stamps/create'
      preLoaderRoute: typeof AuthenticatedStampsCreateImport
      parentRoute: typeof AuthenticatedStampsRouteImport
    }
    '/_authenticated/stamps/history': {
      id: '/_authenticated/stamps/history'
      path: '/history'
      fullPath: '/stamps/history'
      preLoaderRoute: typeof AuthenticatedStampsHistoryImport
      parentRoute: typeof AuthenticatedStampsRouteImport
    }
    '/_authenticated/work-schedules/$id': {
      id: '/_authenticated/work-schedules/$id'
      path: '/$id'
      fullPath: '/work-schedules/$id'
      preLoaderRoute: typeof AuthenticatedWorkSchedulesIdImport
      parentRoute: typeof AuthenticatedWorkSchedulesRouteImport
    }
    '/_authenticated/activity-schedule/': {
      id: '/_authenticated/activity-schedule/'
      path: '/'
      fullPath: '/activity-schedule/'
      preLoaderRoute: typeof AuthenticatedActivityScheduleIndexImport
      parentRoute: typeof AuthenticatedActivityScheduleRouteImport
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/request-forms/': {
      id: '/_authenticated/request-forms/'
      path: '/request-forms'
      fullPath: '/request-forms'
      preLoaderRoute: typeof AuthenticatedRequestFormsIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/scan/': {
      id: '/_authenticated/scan/'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AuthenticatedScanIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/work-schedules/': {
      id: '/_authenticated/work-schedules/'
      path: '/'
      fullPath: '/work-schedules/'
      preLoaderRoute: typeof AuthenticatedWorkSchedulesIndexImport
      parentRoute: typeof AuthenticatedWorkSchedulesRouteImport
    }
    '/_authenticated/admin/attendances/history': {
      id: '/_authenticated/admin/attendances/history'
      path: '/attendances/history'
      fullPath: '/admin/attendances/history'
      preLoaderRoute: typeof AuthenticatedAdminAttendancesHistoryImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/admin/attendances/record': {
      id: '/_authenticated/admin/attendances/record'
      path: '/attendances/record'
      fullPath: '/admin/attendances/record'
      preLoaderRoute: typeof AuthenticatedAdminAttendancesRecordImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/admin/check-po/add': {
      id: '/_authenticated/admin/check-po/add'
      path: '/check-po/add'
      fullPath: '/admin/check-po/add'
      preLoaderRoute: typeof AuthenticatedAdminCheckPoAddImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/admin/check-po/add-export': {
      id: '/_authenticated/admin/check-po/add-export'
      path: '/check-po/add-export'
      fullPath: '/admin/check-po/add-export'
      preLoaderRoute: typeof AuthenticatedAdminCheckPoAddExportImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/admin/check-po/add-inventory': {
      id: '/_authenticated/admin/check-po/add-inventory'
      path: '/check-po/add-inventory'
      fullPath: '/admin/check-po/add-inventory'
      preLoaderRoute: typeof AuthenticatedAdminCheckPoAddInventoryImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/admin/check-po/history': {
      id: '/_authenticated/admin/check-po/history'
      path: '/check-po/history'
      fullPath: '/admin/check-po/history'
      preLoaderRoute: typeof AuthenticatedAdminCheckPoHistoryImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/admin/employees/add': {
      id: '/_authenticated/admin/employees/add'
      path: '/employees/add'
      fullPath: '/admin/employees/add'
      preLoaderRoute: typeof AuthenticatedAdminEmployeesAddImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/admin/plans/material': {
      id: '/_authenticated/admin/plans/material'
      path: '/plans/material'
      fullPath: '/admin/plans/material'
      preLoaderRoute: typeof AuthenticatedAdminPlansMaterialImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/admin/plans/production': {
      id: '/_authenticated/admin/plans/production'
      path: '/plans/production'
      fullPath: '/admin/plans/production'
      preLoaderRoute: typeof AuthenticatedAdminPlansProductionImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/admin/products/$id': {
      id: '/_authenticated/admin/products/$id'
      path: '/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AuthenticatedAdminProductsIdImport
      parentRoute: typeof AuthenticatedAdminProductsRouteImport
    }
    '/_authenticated/admin/products/add': {
      id: '/_authenticated/admin/products/add'
      path: '/add'
      fullPath: '/admin/products/add'
      preLoaderRoute: typeof AuthenticatedAdminProductsAddImport
      parentRoute: typeof AuthenticatedAdminProductsRouteImport
    }
    '/_authenticated/admin/products/trash': {
      id: '/_authenticated/admin/products/trash'
      path: '/trash'
      fullPath: '/admin/products/trash'
      preLoaderRoute: typeof AuthenticatedAdminProductsTrashImport
      parentRoute: typeof AuthenticatedAdminProductsRouteImport
    }
    '/_authenticated/employee/request-forms/authorized': {
      id: '/_authenticated/employee/request-forms/authorized'
      path: '/authorized'
      fullPath: '/employee/request-forms/authorized'
      preLoaderRoute: typeof AuthenticatedEmployeeRequestFormsAuthorizedImport
      parentRoute: typeof AuthenticatedEmployeeRequestFormsRouteImport
    }
    '/_authenticated/employee/salaries/$id': {
      id: '/_authenticated/employee/salaries/$id'
      path: '/salaries/$id'
      fullPath: '/employee/salaries/$id'
      preLoaderRoute: typeof AuthenticatedEmployeeSalariesIdImport
      parentRoute: typeof AuthenticatedEmployeeRouteImport
    }
    '/_authenticated/employee/schedules/$id': {
      id: '/_authenticated/employee/schedules/$id'
      path: '/schedules/$id'
      fullPath: '/employee/schedules/$id'
      preLoaderRoute: typeof AuthenticatedEmployeeSchedulesIdImport
      parentRoute: typeof AuthenticatedEmployeeRouteImport
    }
    '/_authenticated/employee/stamps/history': {
      id: '/_authenticated/employee/stamps/history'
      path: '/stamps/history'
      fullPath: '/employee/stamps/history'
      preLoaderRoute: typeof AuthenticatedEmployeeStampsHistoryImport
      parentRoute: typeof AuthenticatedEmployeeRouteImport
    }
    '/_authenticated/employee/stamps/request': {
      id: '/_authenticated/employee/stamps/request'
      path: '/stamps/request'
      fullPath: '/employee/stamps/request'
      preLoaderRoute: typeof AuthenticatedEmployeeStampsRequestImport
      parentRoute: typeof AuthenticatedEmployeeRouteImport
    }
    '/_authenticated/employee/todo/add-product': {
      id: '/_authenticated/employee/todo/add-product'
      path: '/todo/add-product'
      fullPath: '/employee/todo/add-product'
      preLoaderRoute: typeof AuthenticatedEmployeeTodoAddProductImport
      parentRoute: typeof AuthenticatedEmployeeRouteImport
    }
    '/_authenticated/employee/todo/history': {
      id: '/_authenticated/employee/todo/history'
      path: '/todo/history'
      fullPath: '/employee/todo/history'
      preLoaderRoute: typeof AuthenticatedEmployeeTodoHistoryImport
      parentRoute: typeof AuthenticatedEmployeeRouteImport
    }
    '/_authenticated/employee/todo/update-quantity': {
      id: '/_authenticated/employee/todo/update-quantity'
      path: '/todo/update-quantity'
      fullPath: '/employee/todo/update-quantity'
      preLoaderRoute: typeof AuthenticatedEmployeeTodoUpdateQuantityImport
      parentRoute: typeof AuthenticatedEmployeeRouteImport
    }
    '/_authenticated/employee/todo/update-quantity-error': {
      id: '/_authenticated/employee/todo/update-quantity-error'
      path: '/todo/update-quantity-error'
      fullPath: '/employee/todo/update-quantity-error'
      preLoaderRoute: typeof AuthenticatedEmployeeTodoUpdateQuantityErrorImport
      parentRoute: typeof AuthenticatedEmployeeRouteImport
    }
    '/_authenticated/admin/salaries/$id': {
      id: '/_authenticated/admin/salaries/$id'
      path: '/$id'
      fullPath: '/admin/salaries/$id'
      preLoaderRoute: typeof AuthenticatedAdminSalariesIdLazyImport
      parentRoute: typeof AuthenticatedAdminSalariesRouteImport
    }
    '/_authenticated/admin/check-po/': {
      id: '/_authenticated/admin/check-po/'
      path: '/check-po'
      fullPath: '/admin/check-po'
      preLoaderRoute: typeof AuthenticatedAdminCheckPoIndexImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/admin/edit-layout/': {
      id: '/_authenticated/admin/edit-layout/'
      path: '/edit-layout'
      fullPath: '/admin/edit-layout'
      preLoaderRoute: typeof AuthenticatedAdminEditLayoutIndexImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/admin/employees/': {
      id: '/_authenticated/admin/employees/'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AuthenticatedAdminEmployeesIndexImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/admin/history/': {
      id: '/_authenticated/admin/history/'
      path: '/history'
      fullPath: '/admin/history'
      preLoaderRoute: typeof AuthenticatedAdminHistoryIndexImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/admin/products/': {
      id: '/_authenticated/admin/products/'
      path: '/'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AuthenticatedAdminProductsIndexImport
      parentRoute: typeof AuthenticatedAdminProductsRouteImport
    }
    '/_authenticated/admin/roles/': {
      id: '/_authenticated/admin/roles/'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesIndexImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/admin/salaries/': {
      id: '/_authenticated/admin/salaries/'
      path: '/'
      fullPath: '/admin/salaries/'
      preLoaderRoute: typeof AuthenticatedAdminSalariesIndexImport
      parentRoute: typeof AuthenticatedAdminSalariesRouteImport
    }
    '/_authenticated/admin/work-schedule-categories/': {
      id: '/_authenticated/admin/work-schedule-categories/'
      path: '/work-schedule-categories'
      fullPath: '/admin/work-schedule-categories'
      preLoaderRoute: typeof AuthenticatedAdminWorkScheduleCategoriesIndexImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/employee/activity-schedule/': {
      id: '/_authenticated/employee/activity-schedule/'
      path: '/activity-schedule'
      fullPath: '/employee/activity-schedule'
      preLoaderRoute: typeof AuthenticatedEmployeeActivityScheduleIndexImport
      parentRoute: typeof AuthenticatedEmployeeRouteImport
    }
    '/_authenticated/employee/request-forms/': {
      id: '/_authenticated/employee/request-forms/'
      path: '/'
      fullPath: '/employee/request-forms/'
      preLoaderRoute: typeof AuthenticatedEmployeeRequestFormsIndexImport
      parentRoute: typeof AuthenticatedEmployeeRequestFormsRouteImport
    }
    '/_authenticated/employee/salaries/': {
      id: '/_authenticated/employee/salaries/'
      path: '/salaries'
      fullPath: '/employee/salaries'
      preLoaderRoute: typeof AuthenticatedEmployeeSalariesIndexImport
      parentRoute: typeof AuthenticatedEmployeeRouteImport
    }
    '/_authenticated/employee/schedules/': {
      id: '/_authenticated/employee/schedules/'
      path: '/schedules'
      fullPath: '/employee/schedules'
      preLoaderRoute: typeof AuthenticatedEmployeeSchedulesIndexImport
      parentRoute: typeof AuthenticatedEmployeeRouteImport
    }
    '/_authenticated/admin/employees/edit/$id': {
      id: '/_authenticated/admin/employees/edit/$id'
      path: '/employees/edit/$id'
      fullPath: '/admin/employees/edit/$id'
      preLoaderRoute: typeof AuthenticatedAdminEmployeesEditIdImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/admin/products/edit/$id': {
      id: '/_authenticated/admin/products/edit/$id'
      path: '/edit/$id'
      fullPath: '/admin/products/edit/$id'
      preLoaderRoute: typeof AuthenticatedAdminProductsEditIdImport
      parentRoute: typeof AuthenticatedAdminProductsRouteImport
    }
    '/_authenticated/admin/products/quantity/add': {
      id: '/_authenticated/admin/products/quantity/add'
      path: '/quantity/add'
      fullPath: '/admin/products/quantity/add'
      preLoaderRoute: typeof AuthenticatedAdminProductsQuantityAddImport
      parentRoute: typeof AuthenticatedAdminProductsRouteImport
    }
    '/_authenticated/admin/products/quantity/update': {
      id: '/_authenticated/admin/products/quantity/update'
      path: '/quantity/update'
      fullPath: '/admin/products/quantity/update'
      preLoaderRoute: typeof AuthenticatedAdminProductsQuantityUpdateImport
      parentRoute: typeof AuthenticatedAdminProductsRouteImport
    }
    '/_authenticated/admin/employees/trash/': {
      id: '/_authenticated/admin/employees/trash/'
      path: '/employees/trash'
      fullPath: '/admin/employees/trash'
      preLoaderRoute: typeof AuthenticatedAdminEmployeesTrashIndexImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/employee/attendances/calculate/': {
      id: '/_authenticated/employee/attendances/calculate/'
      path: '/attendances/calculate'
      fullPath: '/employee/attendances/calculate'
      preLoaderRoute: typeof AuthenticatedEmployeeAttendancesCalculateIndexImport
      parentRoute: typeof AuthenticatedEmployeeRouteImport
    }
    '/_authenticated/employee/attendances/history/': {
      id: '/_authenticated/employee/attendances/history/'
      path: '/attendances/history'
      fullPath: '/employee/attendances/history'
      preLoaderRoute: typeof AuthenticatedEmployeeAttendancesHistoryIndexImport
      parentRoute: typeof AuthenticatedEmployeeRouteImport
    }
  }
}

// Create and export the route tree

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface AuthenticatedActivityScheduleRouteRouteChildren {
  AuthenticatedActivityScheduleIndexRoute: typeof AuthenticatedActivityScheduleIndexRoute
}

const AuthenticatedActivityScheduleRouteRouteChildren: AuthenticatedActivityScheduleRouteRouteChildren =
  {
    AuthenticatedActivityScheduleIndexRoute:
      AuthenticatedActivityScheduleIndexRoute,
  }

const AuthenticatedActivityScheduleRouteRouteWithChildren =
  AuthenticatedActivityScheduleRouteRoute._addFileChildren(
    AuthenticatedActivityScheduleRouteRouteChildren,
  )

interface AuthenticatedAdminProductsRouteRouteChildren {
  AuthenticatedAdminProductsIdRoute: typeof AuthenticatedAdminProductsIdRoute
  AuthenticatedAdminProductsAddRoute: typeof AuthenticatedAdminProductsAddRoute
  AuthenticatedAdminProductsTrashRoute: typeof AuthenticatedAdminProductsTrashRoute
  AuthenticatedAdminProductsIndexRoute: typeof AuthenticatedAdminProductsIndexRoute
  AuthenticatedAdminProductsEditIdRoute: typeof AuthenticatedAdminProductsEditIdRoute
  AuthenticatedAdminProductsQuantityAddRoute: typeof AuthenticatedAdminProductsQuantityAddRoute
  AuthenticatedAdminProductsQuantityUpdateRoute: typeof AuthenticatedAdminProductsQuantityUpdateRoute
}

const AuthenticatedAdminProductsRouteRouteChildren: AuthenticatedAdminProductsRouteRouteChildren =
  {
    AuthenticatedAdminProductsIdRoute: AuthenticatedAdminProductsIdRoute,
    AuthenticatedAdminProductsAddRoute: AuthenticatedAdminProductsAddRoute,
    AuthenticatedAdminProductsTrashRoute: AuthenticatedAdminProductsTrashRoute,
    AuthenticatedAdminProductsIndexRoute: AuthenticatedAdminProductsIndexRoute,
    AuthenticatedAdminProductsEditIdRoute:
      AuthenticatedAdminProductsEditIdRoute,
    AuthenticatedAdminProductsQuantityAddRoute:
      AuthenticatedAdminProductsQuantityAddRoute,
    AuthenticatedAdminProductsQuantityUpdateRoute:
      AuthenticatedAdminProductsQuantityUpdateRoute,
  }

const AuthenticatedAdminProductsRouteRouteWithChildren =
  AuthenticatedAdminProductsRouteRoute._addFileChildren(
    AuthenticatedAdminProductsRouteRouteChildren,
  )

interface AuthenticatedAdminSalariesRouteRouteChildren {
  AuthenticatedAdminSalariesIdLazyRoute: typeof AuthenticatedAdminSalariesIdLazyRoute
  AuthenticatedAdminSalariesIndexRoute: typeof AuthenticatedAdminSalariesIndexRoute
}

const AuthenticatedAdminSalariesRouteRouteChildren: AuthenticatedAdminSalariesRouteRouteChildren =
  {
    AuthenticatedAdminSalariesIdLazyRoute:
      AuthenticatedAdminSalariesIdLazyRoute,
    AuthenticatedAdminSalariesIndexRoute: AuthenticatedAdminSalariesIndexRoute,
  }

const AuthenticatedAdminSalariesRouteRouteWithChildren =
  AuthenticatedAdminSalariesRouteRoute._addFileChildren(
    AuthenticatedAdminSalariesRouteRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminProductsRouteRoute: typeof AuthenticatedAdminProductsRouteRouteWithChildren
  AuthenticatedAdminSalariesRouteRoute: typeof AuthenticatedAdminSalariesRouteRouteWithChildren
  AuthenticatedAdminAboutRoute: typeof AuthenticatedAdminAboutRoute
  AuthenticatedAdminNotificationDemoRoute: typeof AuthenticatedAdminNotificationDemoRoute
  AuthenticatedAdminAttendancesHistoryRoute: typeof AuthenticatedAdminAttendancesHistoryRoute
  AuthenticatedAdminAttendancesRecordRoute: typeof AuthenticatedAdminAttendancesRecordRoute
  AuthenticatedAdminCheckPoAddRoute: typeof AuthenticatedAdminCheckPoAddRoute
  AuthenticatedAdminCheckPoAddExportRoute: typeof AuthenticatedAdminCheckPoAddExportRoute
  AuthenticatedAdminCheckPoAddInventoryRoute: typeof AuthenticatedAdminCheckPoAddInventoryRoute
  AuthenticatedAdminCheckPoHistoryRoute: typeof AuthenticatedAdminCheckPoHistoryRoute
  AuthenticatedAdminEmployeesAddRoute: typeof AuthenticatedAdminEmployeesAddRoute
  AuthenticatedAdminPlansMaterialRoute: typeof AuthenticatedAdminPlansMaterialRoute
  AuthenticatedAdminPlansProductionRoute: typeof AuthenticatedAdminPlansProductionRoute
  AuthenticatedAdminCheckPoIndexRoute: typeof AuthenticatedAdminCheckPoIndexRoute
  AuthenticatedAdminEditLayoutIndexRoute: typeof AuthenticatedAdminEditLayoutIndexRoute
  AuthenticatedAdminEmployeesIndexRoute: typeof AuthenticatedAdminEmployeesIndexRoute
  AuthenticatedAdminHistoryIndexRoute: typeof AuthenticatedAdminHistoryIndexRoute
  AuthenticatedAdminRolesIndexRoute: typeof AuthenticatedAdminRolesIndexRoute
  AuthenticatedAdminWorkScheduleCategoriesIndexRoute: typeof AuthenticatedAdminWorkScheduleCategoriesIndexRoute
  AuthenticatedAdminEmployeesEditIdRoute: typeof AuthenticatedAdminEmployeesEditIdRoute
  AuthenticatedAdminEmployeesTrashIndexRoute: typeof AuthenticatedAdminEmployeesTrashIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminProductsRouteRoute:
      AuthenticatedAdminProductsRouteRouteWithChildren,
    AuthenticatedAdminSalariesRouteRoute:
      AuthenticatedAdminSalariesRouteRouteWithChildren,
    AuthenticatedAdminAboutRoute: AuthenticatedAdminAboutRoute,
    AuthenticatedAdminNotificationDemoRoute:
      AuthenticatedAdminNotificationDemoRoute,
    AuthenticatedAdminAttendancesHistoryRoute:
      AuthenticatedAdminAttendancesHistoryRoute,
    AuthenticatedAdminAttendancesRecordRoute:
      AuthenticatedAdminAttendancesRecordRoute,
    AuthenticatedAdminCheckPoAddRoute: AuthenticatedAdminCheckPoAddRoute,
    AuthenticatedAdminCheckPoAddExportRoute:
      AuthenticatedAdminCheckPoAddExportRoute,
    AuthenticatedAdminCheckPoAddInventoryRoute:
      AuthenticatedAdminCheckPoAddInventoryRoute,
    AuthenticatedAdminCheckPoHistoryRoute:
      AuthenticatedAdminCheckPoHistoryRoute,
    AuthenticatedAdminEmployeesAddRoute: AuthenticatedAdminEmployeesAddRoute,
    AuthenticatedAdminPlansMaterialRoute: AuthenticatedAdminPlansMaterialRoute,
    AuthenticatedAdminPlansProductionRoute:
      AuthenticatedAdminPlansProductionRoute,
    AuthenticatedAdminCheckPoIndexRoute: AuthenticatedAdminCheckPoIndexRoute,
    AuthenticatedAdminEditLayoutIndexRoute:
      AuthenticatedAdminEditLayoutIndexRoute,
    AuthenticatedAdminEmployeesIndexRoute:
      AuthenticatedAdminEmployeesIndexRoute,
    AuthenticatedAdminHistoryIndexRoute: AuthenticatedAdminHistoryIndexRoute,
    AuthenticatedAdminRolesIndexRoute: AuthenticatedAdminRolesIndexRoute,
    AuthenticatedAdminWorkScheduleCategoriesIndexRoute:
      AuthenticatedAdminWorkScheduleCategoriesIndexRoute,
    AuthenticatedAdminEmployeesEditIdRoute:
      AuthenticatedAdminEmployeesEditIdRoute,
    AuthenticatedAdminEmployeesTrashIndexRoute:
      AuthenticatedAdminEmployeesTrashIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedEmployeeRequestFormsRouteRouteChildren {
  AuthenticatedEmployeeRequestFormsAuthorizedRoute: typeof AuthenticatedEmployeeRequestFormsAuthorizedRoute
  AuthenticatedEmployeeRequestFormsIndexRoute: typeof AuthenticatedEmployeeRequestFormsIndexRoute
}

const AuthenticatedEmployeeRequestFormsRouteRouteChildren: AuthenticatedEmployeeRequestFormsRouteRouteChildren =
  {
    AuthenticatedEmployeeRequestFormsAuthorizedRoute:
      AuthenticatedEmployeeRequestFormsAuthorizedRoute,
    AuthenticatedEmployeeRequestFormsIndexRoute:
      AuthenticatedEmployeeRequestFormsIndexRoute,
  }

const AuthenticatedEmployeeRequestFormsRouteRouteWithChildren =
  AuthenticatedEmployeeRequestFormsRouteRoute._addFileChildren(
    AuthenticatedEmployeeRequestFormsRouteRouteChildren,
  )

interface AuthenticatedEmployeeRouteRouteChildren {
  AuthenticatedEmployeeRequestFormsRouteRoute: typeof AuthenticatedEmployeeRequestFormsRouteRouteWithChildren
  AuthenticatedEmployeeSalariesIdRoute: typeof AuthenticatedEmployeeSalariesIdRoute
  AuthenticatedEmployeeSchedulesIdRoute: typeof AuthenticatedEmployeeSchedulesIdRoute
  AuthenticatedEmployeeStampsHistoryRoute: typeof AuthenticatedEmployeeStampsHistoryRoute
  AuthenticatedEmployeeStampsRequestRoute: typeof AuthenticatedEmployeeStampsRequestRoute
  AuthenticatedEmployeeTodoAddProductRoute: typeof AuthenticatedEmployeeTodoAddProductRoute
  AuthenticatedEmployeeTodoHistoryRoute: typeof AuthenticatedEmployeeTodoHistoryRoute
  AuthenticatedEmployeeTodoUpdateQuantityRoute: typeof AuthenticatedEmployeeTodoUpdateQuantityRoute
  AuthenticatedEmployeeTodoUpdateQuantityErrorRoute: typeof AuthenticatedEmployeeTodoUpdateQuantityErrorRoute
  AuthenticatedEmployeeActivityScheduleIndexRoute: typeof AuthenticatedEmployeeActivityScheduleIndexRoute
  AuthenticatedEmployeeSalariesIndexRoute: typeof AuthenticatedEmployeeSalariesIndexRoute
  AuthenticatedEmployeeSchedulesIndexRoute: typeof AuthenticatedEmployeeSchedulesIndexRoute
  AuthenticatedEmployeeAttendancesCalculateIndexRoute: typeof AuthenticatedEmployeeAttendancesCalculateIndexRoute
  AuthenticatedEmployeeAttendancesHistoryIndexRoute: typeof AuthenticatedEmployeeAttendancesHistoryIndexRoute
}

const AuthenticatedEmployeeRouteRouteChildren: AuthenticatedEmployeeRouteRouteChildren =
  {
    AuthenticatedEmployeeRequestFormsRouteRoute:
      AuthenticatedEmployeeRequestFormsRouteRouteWithChildren,
    AuthenticatedEmployeeSalariesIdRoute: AuthenticatedEmployeeSalariesIdRoute,
    AuthenticatedEmployeeSchedulesIdRoute:
      AuthenticatedEmployeeSchedulesIdRoute,
    AuthenticatedEmployeeStampsHistoryRoute:
      AuthenticatedEmployeeStampsHistoryRoute,
    AuthenticatedEmployeeStampsRequestRoute:
      AuthenticatedEmployeeStampsRequestRoute,
    AuthenticatedEmployeeTodoAddProductRoute:
      AuthenticatedEmployeeTodoAddProductRoute,
    AuthenticatedEmployeeTodoHistoryRoute:
      AuthenticatedEmployeeTodoHistoryRoute,
    AuthenticatedEmployeeTodoUpdateQuantityRoute:
      AuthenticatedEmployeeTodoUpdateQuantityRoute,
    AuthenticatedEmployeeTodoUpdateQuantityErrorRoute:
      AuthenticatedEmployeeTodoUpdateQuantityErrorRoute,
    AuthenticatedEmployeeActivityScheduleIndexRoute:
      AuthenticatedEmployeeActivityScheduleIndexRoute,
    AuthenticatedEmployeeSalariesIndexRoute:
      AuthenticatedEmployeeSalariesIndexRoute,
    AuthenticatedEmployeeSchedulesIndexRoute:
      AuthenticatedEmployeeSchedulesIndexRoute,
    AuthenticatedEmployeeAttendancesCalculateIndexRoute:
      AuthenticatedEmployeeAttendancesCalculateIndexRoute,
    AuthenticatedEmployeeAttendancesHistoryIndexRoute:
      AuthenticatedEmployeeAttendancesHistoryIndexRoute,
  }

const AuthenticatedEmployeeRouteRouteWithChildren =
  AuthenticatedEmployeeRouteRoute._addFileChildren(
    AuthenticatedEmployeeRouteRouteChildren,
  )

interface AuthenticatedStampsRouteRouteChildren {
  AuthenticatedStampsCreateRoute: typeof AuthenticatedStampsCreateRoute
  AuthenticatedStampsHistoryRoute: typeof AuthenticatedStampsHistoryRoute
}

const AuthenticatedStampsRouteRouteChildren: AuthenticatedStampsRouteRouteChildren =
  {
    AuthenticatedStampsCreateRoute: AuthenticatedStampsCreateRoute,
    AuthenticatedStampsHistoryRoute: AuthenticatedStampsHistoryRoute,
  }

const AuthenticatedStampsRouteRouteWithChildren =
  AuthenticatedStampsRouteRoute._addFileChildren(
    AuthenticatedStampsRouteRouteChildren,
  )

interface AuthenticatedWorkSchedulesRouteRouteChildren {
  AuthenticatedWorkSchedulesIdRoute: typeof AuthenticatedWorkSchedulesIdRoute
  AuthenticatedWorkSchedulesIndexRoute: typeof AuthenticatedWorkSchedulesIndexRoute
}

const AuthenticatedWorkSchedulesRouteRouteChildren: AuthenticatedWorkSchedulesRouteRouteChildren =
  {
    AuthenticatedWorkSchedulesIdRoute: AuthenticatedWorkSchedulesIdRoute,
    AuthenticatedWorkSchedulesIndexRoute: AuthenticatedWorkSchedulesIndexRoute,
  }

const AuthenticatedWorkSchedulesRouteRouteWithChildren =
  AuthenticatedWorkSchedulesRouteRoute._addFileChildren(
    AuthenticatedWorkSchedulesRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedActivityScheduleRouteRoute: typeof AuthenticatedActivityScheduleRouteRouteWithChildren
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedEmployeeRouteRoute: typeof AuthenticatedEmployeeRouteRouteWithChildren
  AuthenticatedStampsRouteRoute: typeof AuthenticatedStampsRouteRouteWithChildren
  AuthenticatedWorkSchedulesRouteRoute: typeof AuthenticatedWorkSchedulesRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedRequestFormsIdRoute: typeof AuthenticatedRequestFormsIdRoute
  AuthenticatedScanStorageRoute: typeof AuthenticatedScanStorageRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
  AuthenticatedRequestFormsIndexRoute: typeof AuthenticatedRequestFormsIndexRoute
  AuthenticatedScanIndexRoute: typeof AuthenticatedScanIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedActivityScheduleRouteRoute:
    AuthenticatedActivityScheduleRouteRouteWithChildren,
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedEmployeeRouteRoute: AuthenticatedEmployeeRouteRouteWithChildren,
  AuthenticatedStampsRouteRoute: AuthenticatedStampsRouteRouteWithChildren,
  AuthenticatedWorkSchedulesRouteRoute:
    AuthenticatedWorkSchedulesRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedRequestFormsIdRoute: AuthenticatedRequestFormsIdRoute,
  AuthenticatedScanStorageRoute: AuthenticatedScanStorageRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
  AuthenticatedRequestFormsIndexRoute: AuthenticatedRequestFormsIndexRoute,
  AuthenticatedScanIndexRoute: AuthenticatedScanIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/activity-schedule': typeof AuthenticatedActivityScheduleRouteRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/employee': typeof AuthenticatedEmployeeRouteRouteWithChildren
  '/stamps': typeof AuthenticatedStampsRouteRouteWithChildren
  '/work-schedules': typeof AuthenticatedWorkSchedulesRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/admin/products': typeof AuthenticatedAdminProductsRouteRouteWithChildren
  '/admin/salaries': typeof AuthenticatedAdminSalariesRouteRouteWithChildren
  '/employee/request-forms': typeof AuthenticatedEmployeeRequestFormsRouteRouteWithChildren
  '/admin/about': typeof AuthenticatedAdminAboutRoute
  '/admin/notification-demo': typeof AuthenticatedAdminNotificationDemoRoute
  '/request-forms/$id': typeof AuthenticatedRequestFormsIdRoute
  '/scan/storage': typeof AuthenticatedScanStorageRoute
  '/stamps/create': typeof AuthenticatedStampsCreateRoute
  '/stamps/history': typeof AuthenticatedStampsHistoryRoute
  '/work-schedules/$id': typeof AuthenticatedWorkSchedulesIdRoute
  '/activity-schedule/': typeof AuthenticatedActivityScheduleIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/request-forms': typeof AuthenticatedRequestFormsIndexRoute
  '/scan': typeof AuthenticatedScanIndexRoute
  '/work-schedules/': typeof AuthenticatedWorkSchedulesIndexRoute
  '/admin/attendances/history': typeof AuthenticatedAdminAttendancesHistoryRoute
  '/admin/attendances/record': typeof AuthenticatedAdminAttendancesRecordRoute
  '/admin/check-po/add': typeof AuthenticatedAdminCheckPoAddRoute
  '/admin/check-po/add-export': typeof AuthenticatedAdminCheckPoAddExportRoute
  '/admin/check-po/add-inventory': typeof AuthenticatedAdminCheckPoAddInventoryRoute
  '/admin/check-po/history': typeof AuthenticatedAdminCheckPoHistoryRoute
  '/admin/employees/add': typeof AuthenticatedAdminEmployeesAddRoute
  '/admin/plans/material': typeof AuthenticatedAdminPlansMaterialRoute
  '/admin/plans/production': typeof AuthenticatedAdminPlansProductionRoute
  '/admin/products/$id': typeof AuthenticatedAdminProductsIdRoute
  '/admin/products/add': typeof AuthenticatedAdminProductsAddRoute
  '/admin/products/trash': typeof AuthenticatedAdminProductsTrashRoute
  '/employee/request-forms/authorized': typeof AuthenticatedEmployeeRequestFormsAuthorizedRoute
  '/employee/salaries/$id': typeof AuthenticatedEmployeeSalariesIdRoute
  '/employee/schedules/$id': typeof AuthenticatedEmployeeSchedulesIdRoute
  '/employee/stamps/history': typeof AuthenticatedEmployeeStampsHistoryRoute
  '/employee/stamps/request': typeof AuthenticatedEmployeeStampsRequestRoute
  '/employee/todo/add-product': typeof AuthenticatedEmployeeTodoAddProductRoute
  '/employee/todo/history': typeof AuthenticatedEmployeeTodoHistoryRoute
  '/employee/todo/update-quantity': typeof AuthenticatedEmployeeTodoUpdateQuantityRoute
  '/employee/todo/update-quantity-error': typeof AuthenticatedEmployeeTodoUpdateQuantityErrorRoute
  '/admin/salaries/$id': typeof AuthenticatedAdminSalariesIdLazyRoute
  '/admin/check-po': typeof AuthenticatedAdminCheckPoIndexRoute
  '/admin/edit-layout': typeof AuthenticatedAdminEditLayoutIndexRoute
  '/admin/employees': typeof AuthenticatedAdminEmployeesIndexRoute
  '/admin/history': typeof AuthenticatedAdminHistoryIndexRoute
  '/admin/products/': typeof AuthenticatedAdminProductsIndexRoute
  '/admin/roles': typeof AuthenticatedAdminRolesIndexRoute
  '/admin/salaries/': typeof AuthenticatedAdminSalariesIndexRoute
  '/admin/work-schedule-categories': typeof AuthenticatedAdminWorkScheduleCategoriesIndexRoute
  '/employee/activity-schedule': typeof AuthenticatedEmployeeActivityScheduleIndexRoute
  '/employee/request-forms/': typeof AuthenticatedEmployeeRequestFormsIndexRoute
  '/employee/salaries': typeof AuthenticatedEmployeeSalariesIndexRoute
  '/employee/schedules': typeof AuthenticatedEmployeeSchedulesIndexRoute
  '/admin/employees/edit/$id': typeof AuthenticatedAdminEmployeesEditIdRoute
  '/admin/products/edit/$id': typeof AuthenticatedAdminProductsEditIdRoute
  '/admin/products/quantity/add': typeof AuthenticatedAdminProductsQuantityAddRoute
  '/admin/products/quantity/update': typeof AuthenticatedAdminProductsQuantityUpdateRoute
  '/admin/employees/trash': typeof AuthenticatedAdminEmployeesTrashIndexRoute
  '/employee/attendances/calculate': typeof AuthenticatedEmployeeAttendancesCalculateIndexRoute
  '/employee/attendances/history': typeof AuthenticatedEmployeeAttendancesHistoryIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/employee': typeof AuthenticatedEmployeeRouteRouteWithChildren
  '/stamps': typeof AuthenticatedStampsRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/admin/about': typeof AuthenticatedAdminAboutRoute
  '/admin/notification-demo': typeof AuthenticatedAdminNotificationDemoRoute
  '/request-forms/$id': typeof AuthenticatedRequestFormsIdRoute
  '/scan/storage': typeof AuthenticatedScanStorageRoute
  '/stamps/create': typeof AuthenticatedStampsCreateRoute
  '/stamps/history': typeof AuthenticatedStampsHistoryRoute
  '/work-schedules/$id': typeof AuthenticatedWorkSchedulesIdRoute
  '/activity-schedule': typeof AuthenticatedActivityScheduleIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/request-forms': typeof AuthenticatedRequestFormsIndexRoute
  '/scan': typeof AuthenticatedScanIndexRoute
  '/work-schedules': typeof AuthenticatedWorkSchedulesIndexRoute
  '/admin/attendances/history': typeof AuthenticatedAdminAttendancesHistoryRoute
  '/admin/attendances/record': typeof AuthenticatedAdminAttendancesRecordRoute
  '/admin/check-po/add': typeof AuthenticatedAdminCheckPoAddRoute
  '/admin/check-po/add-export': typeof AuthenticatedAdminCheckPoAddExportRoute
  '/admin/check-po/add-inventory': typeof AuthenticatedAdminCheckPoAddInventoryRoute
  '/admin/check-po/history': typeof AuthenticatedAdminCheckPoHistoryRoute
  '/admin/employees/add': typeof AuthenticatedAdminEmployeesAddRoute
  '/admin/plans/material': typeof AuthenticatedAdminPlansMaterialRoute
  '/admin/plans/production': typeof AuthenticatedAdminPlansProductionRoute
  '/admin/products/$id': typeof AuthenticatedAdminProductsIdRoute
  '/admin/products/add': typeof AuthenticatedAdminProductsAddRoute
  '/admin/products/trash': typeof AuthenticatedAdminProductsTrashRoute
  '/employee/request-forms/authorized': typeof AuthenticatedEmployeeRequestFormsAuthorizedRoute
  '/employee/salaries/$id': typeof AuthenticatedEmployeeSalariesIdRoute
  '/employee/schedules/$id': typeof AuthenticatedEmployeeSchedulesIdRoute
  '/employee/stamps/history': typeof AuthenticatedEmployeeStampsHistoryRoute
  '/employee/stamps/request': typeof AuthenticatedEmployeeStampsRequestRoute
  '/employee/todo/add-product': typeof AuthenticatedEmployeeTodoAddProductRoute
  '/employee/todo/history': typeof AuthenticatedEmployeeTodoHistoryRoute
  '/employee/todo/update-quantity': typeof AuthenticatedEmployeeTodoUpdateQuantityRoute
  '/employee/todo/update-quantity-error': typeof AuthenticatedEmployeeTodoUpdateQuantityErrorRoute
  '/admin/salaries/$id': typeof AuthenticatedAdminSalariesIdLazyRoute
  '/admin/check-po': typeof AuthenticatedAdminCheckPoIndexRoute
  '/admin/edit-layout': typeof AuthenticatedAdminEditLayoutIndexRoute
  '/admin/employees': typeof AuthenticatedAdminEmployeesIndexRoute
  '/admin/history': typeof AuthenticatedAdminHistoryIndexRoute
  '/admin/products': typeof AuthenticatedAdminProductsIndexRoute
  '/admin/roles': typeof AuthenticatedAdminRolesIndexRoute
  '/admin/salaries': typeof AuthenticatedAdminSalariesIndexRoute
  '/admin/work-schedule-categories': typeof AuthenticatedAdminWorkScheduleCategoriesIndexRoute
  '/employee/activity-schedule': typeof AuthenticatedEmployeeActivityScheduleIndexRoute
  '/employee/request-forms': typeof AuthenticatedEmployeeRequestFormsIndexRoute
  '/employee/salaries': typeof AuthenticatedEmployeeSalariesIndexRoute
  '/employee/schedules': typeof AuthenticatedEmployeeSchedulesIndexRoute
  '/admin/employees/edit/$id': typeof AuthenticatedAdminEmployeesEditIdRoute
  '/admin/products/edit/$id': typeof AuthenticatedAdminProductsEditIdRoute
  '/admin/products/quantity/add': typeof AuthenticatedAdminProductsQuantityAddRoute
  '/admin/products/quantity/update': typeof AuthenticatedAdminProductsQuantityUpdateRoute
  '/admin/employees/trash': typeof AuthenticatedAdminEmployeesTrashIndexRoute
  '/employee/attendances/calculate': typeof AuthenticatedEmployeeAttendancesCalculateIndexRoute
  '/employee/attendances/history': typeof AuthenticatedEmployeeAttendancesHistoryIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/_authenticated/activity-schedule': typeof AuthenticatedActivityScheduleRouteRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/employee': typeof AuthenticatedEmployeeRouteRouteWithChildren
  '/_authenticated/stamps': typeof AuthenticatedStampsRouteRouteWithChildren
  '/_authenticated/work-schedules': typeof AuthenticatedWorkSchedulesRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRouteRouteWithChildren
  '/_authenticated/admin/salaries': typeof AuthenticatedAdminSalariesRouteRouteWithChildren
  '/_authenticated/employee/request-forms': typeof AuthenticatedEmployeeRequestFormsRouteRouteWithChildren
  '/_authenticated/admin/about': typeof AuthenticatedAdminAboutRoute
  '/_authenticated/admin/notification-demo': typeof AuthenticatedAdminNotificationDemoRoute
  '/_authenticated/request-forms/$id': typeof AuthenticatedRequestFormsIdRoute
  '/_authenticated/scan/storage': typeof AuthenticatedScanStorageRoute
  '/_authenticated/stamps/create': typeof AuthenticatedStampsCreateRoute
  '/_authenticated/stamps/history': typeof AuthenticatedStampsHistoryRoute
  '/_authenticated/work-schedules/$id': typeof AuthenticatedWorkSchedulesIdRoute
  '/_authenticated/activity-schedule/': typeof AuthenticatedActivityScheduleIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/_authenticated/request-forms/': typeof AuthenticatedRequestFormsIndexRoute
  '/_authenticated/scan/': typeof AuthenticatedScanIndexRoute
  '/_authenticated/work-schedules/': typeof AuthenticatedWorkSchedulesIndexRoute
  '/_authenticated/admin/attendances/history': typeof AuthenticatedAdminAttendancesHistoryRoute
  '/_authenticated/admin/attendances/record': typeof AuthenticatedAdminAttendancesRecordRoute
  '/_authenticated/admin/check-po/add': typeof AuthenticatedAdminCheckPoAddRoute
  '/_authenticated/admin/check-po/add-export': typeof AuthenticatedAdminCheckPoAddExportRoute
  '/_authenticated/admin/check-po/add-inventory': typeof AuthenticatedAdminCheckPoAddInventoryRoute
  '/_authenticated/admin/check-po/history': typeof AuthenticatedAdminCheckPoHistoryRoute
  '/_authenticated/admin/employees/add': typeof AuthenticatedAdminEmployeesAddRoute
  '/_authenticated/admin/plans/material': typeof AuthenticatedAdminPlansMaterialRoute
  '/_authenticated/admin/plans/production': typeof AuthenticatedAdminPlansProductionRoute
  '/_authenticated/admin/products/$id': typeof AuthenticatedAdminProductsIdRoute
  '/_authenticated/admin/products/add': typeof AuthenticatedAdminProductsAddRoute
  '/_authenticated/admin/products/trash': typeof AuthenticatedAdminProductsTrashRoute
  '/_authenticated/employee/request-forms/authorized': typeof AuthenticatedEmployeeRequestFormsAuthorizedRoute
  '/_authenticated/employee/salaries/$id': typeof AuthenticatedEmployeeSalariesIdRoute
  '/_authenticated/employee/schedules/$id': typeof AuthenticatedEmployeeSchedulesIdRoute
  '/_authenticated/employee/stamps/history': typeof AuthenticatedEmployeeStampsHistoryRoute
  '/_authenticated/employee/stamps/request': typeof AuthenticatedEmployeeStampsRequestRoute
  '/_authenticated/employee/todo/add-product': typeof AuthenticatedEmployeeTodoAddProductRoute
  '/_authenticated/employee/todo/history': typeof AuthenticatedEmployeeTodoHistoryRoute
  '/_authenticated/employee/todo/update-quantity': typeof AuthenticatedEmployeeTodoUpdateQuantityRoute
  '/_authenticated/employee/todo/update-quantity-error': typeof AuthenticatedEmployeeTodoUpdateQuantityErrorRoute
  '/_authenticated/admin/salaries/$id': typeof AuthenticatedAdminSalariesIdLazyRoute
  '/_authenticated/admin/check-po/': typeof AuthenticatedAdminCheckPoIndexRoute
  '/_authenticated/admin/edit-layout/': typeof AuthenticatedAdminEditLayoutIndexRoute
  '/_authenticated/admin/employees/': typeof AuthenticatedAdminEmployeesIndexRoute
  '/_authenticated/admin/history/': typeof AuthenticatedAdminHistoryIndexRoute
  '/_authenticated/admin/products/': typeof AuthenticatedAdminProductsIndexRoute
  '/_authenticated/admin/roles/': typeof AuthenticatedAdminRolesIndexRoute
  '/_authenticated/admin/salaries/': typeof AuthenticatedAdminSalariesIndexRoute
  '/_authenticated/admin/work-schedule-categories/': typeof AuthenticatedAdminWorkScheduleCategoriesIndexRoute
  '/_authenticated/employee/activity-schedule/': typeof AuthenticatedEmployeeActivityScheduleIndexRoute
  '/_authenticated/employee/request-forms/': typeof AuthenticatedEmployeeRequestFormsIndexRoute
  '/_authenticated/employee/salaries/': typeof AuthenticatedEmployeeSalariesIndexRoute
  '/_authenticated/employee/schedules/': typeof AuthenticatedEmployeeSchedulesIndexRoute
  '/_authenticated/admin/employees/edit/$id': typeof AuthenticatedAdminEmployeesEditIdRoute
  '/_authenticated/admin/products/edit/$id': typeof AuthenticatedAdminProductsEditIdRoute
  '/_authenticated/admin/products/quantity/add': typeof AuthenticatedAdminProductsQuantityAddRoute
  '/_authenticated/admin/products/quantity/update': typeof AuthenticatedAdminProductsQuantityUpdateRoute
  '/_authenticated/admin/employees/trash/': typeof AuthenticatedAdminEmployeesTrashIndexRoute
  '/_authenticated/employee/attendances/calculate/': typeof AuthenticatedEmployeeAttendancesCalculateIndexRoute
  '/_authenticated/employee/attendances/history/': typeof AuthenticatedEmployeeAttendancesHistoryIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/forbidden'
    | '/activity-schedule'
    | '/admin'
    | '/employee'
    | '/stamps'
    | '/work-schedules'
    | '/login'
    | '/admin/products'
    | '/admin/salaries'
    | '/employee/request-forms'
    | '/admin/about'
    | '/admin/notification-demo'
    | '/request-forms/$id'
    | '/scan/storage'
    | '/stamps/create'
    | '/stamps/history'
    | '/work-schedules/$id'
    | '/activity-schedule/'
    | '/profile'
    | '/request-forms'
    | '/scan'
    | '/work-schedules/'
    | '/admin/attendances/history'
    | '/admin/attendances/record'
    | '/admin/check-po/add'
    | '/admin/check-po/add-export'
    | '/admin/check-po/add-inventory'
    | '/admin/check-po/history'
    | '/admin/employees/add'
    | '/admin/plans/material'
    | '/admin/plans/production'
    | '/admin/products/$id'
    | '/admin/products/add'
    | '/admin/products/trash'
    | '/employee/request-forms/authorized'
    | '/employee/salaries/$id'
    | '/employee/schedules/$id'
    | '/employee/stamps/history'
    | '/employee/stamps/request'
    | '/employee/todo/add-product'
    | '/employee/todo/history'
    | '/employee/todo/update-quantity'
    | '/employee/todo/update-quantity-error'
    | '/admin/salaries/$id'
    | '/admin/check-po'
    | '/admin/edit-layout'
    | '/admin/employees'
    | '/admin/history'
    | '/admin/products/'
    | '/admin/roles'
    | '/admin/salaries/'
    | '/admin/work-schedule-categories'
    | '/employee/activity-schedule'
    | '/employee/request-forms/'
    | '/employee/salaries'
    | '/employee/schedules'
    | '/admin/employees/edit/$id'
    | '/admin/products/edit/$id'
    | '/admin/products/quantity/add'
    | '/admin/products/quantity/update'
    | '/admin/employees/trash'
    | '/employee/attendances/calculate'
    | '/employee/attendances/history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forbidden'
    | '/admin'
    | '/employee'
    | '/stamps'
    | '/login'
    | '/admin/about'
    | '/admin/notification-demo'
    | '/request-forms/$id'
    | '/scan/storage'
    | '/stamps/create'
    | '/stamps/history'
    | '/work-schedules/$id'
    | '/activity-schedule'
    | '/profile'
    | '/request-forms'
    | '/scan'
    | '/work-schedules'
    | '/admin/attendances/history'
    | '/admin/attendances/record'
    | '/admin/check-po/add'
    | '/admin/check-po/add-export'
    | '/admin/check-po/add-inventory'
    | '/admin/check-po/history'
    | '/admin/employees/add'
    | '/admin/plans/material'
    | '/admin/plans/production'
    | '/admin/products/$id'
    | '/admin/products/add'
    | '/admin/products/trash'
    | '/employee/request-forms/authorized'
    | '/employee/salaries/$id'
    | '/employee/schedules/$id'
    | '/employee/stamps/history'
    | '/employee/stamps/request'
    | '/employee/todo/add-product'
    | '/employee/todo/history'
    | '/employee/todo/update-quantity'
    | '/employee/todo/update-quantity-error'
    | '/admin/salaries/$id'
    | '/admin/check-po'
    | '/admin/edit-layout'
    | '/admin/employees'
    | '/admin/history'
    | '/admin/products'
    | '/admin/roles'
    | '/admin/salaries'
    | '/admin/work-schedule-categories'
    | '/employee/activity-schedule'
    | '/employee/request-forms'
    | '/employee/salaries'
    | '/employee/schedules'
    | '/admin/employees/edit/$id'
    | '/admin/products/edit/$id'
    | '/admin/products/quantity/add'
    | '/admin/products/quantity/update'
    | '/admin/employees/trash'
    | '/employee/attendances/calculate'
    | '/employee/attendances/history'
  id:
    | '__root__'
    | '/(auth)'
    | '/_authenticated'
    | '/forbidden'
    | '/_authenticated/activity-schedule'
    | '/_authenticated/admin'
    | '/_authenticated/employee'
    | '/_authenticated/stamps'
    | '/_authenticated/work-schedules'
    | '/(auth)/login'
    | '/_authenticated/'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/salaries'
    | '/_authenticated/employee/request-forms'
    | '/_authenticated/admin/about'
    | '/_authenticated/admin/notification-demo'
    | '/_authenticated/request-forms/$id'
    | '/_authenticated/scan/storage'
    | '/_authenticated/stamps/create'
    | '/_authenticated/stamps/history'
    | '/_authenticated/work-schedules/$id'
    | '/_authenticated/activity-schedule/'
    | '/_authenticated/profile/'
    | '/_authenticated/request-forms/'
    | '/_authenticated/scan/'
    | '/_authenticated/work-schedules/'
    | '/_authenticated/admin/attendances/history'
    | '/_authenticated/admin/attendances/record'
    | '/_authenticated/admin/check-po/add'
    | '/_authenticated/admin/check-po/add-export'
    | '/_authenticated/admin/check-po/add-inventory'
    | '/_authenticated/admin/check-po/history'
    | '/_authenticated/admin/employees/add'
    | '/_authenticated/admin/plans/material'
    | '/_authenticated/admin/plans/production'
    | '/_authenticated/admin/products/$id'
    | '/_authenticated/admin/products/add'
    | '/_authenticated/admin/products/trash'
    | '/_authenticated/employee/request-forms/authorized'
    | '/_authenticated/employee/salaries/$id'
    | '/_authenticated/employee/schedules/$id'
    | '/_authenticated/employee/stamps/history'
    | '/_authenticated/employee/stamps/request'
    | '/_authenticated/employee/todo/add-product'
    | '/_authenticated/employee/todo/history'
    | '/_authenticated/employee/todo/update-quantity'
    | '/_authenticated/employee/todo/update-quantity-error'
    | '/_authenticated/admin/salaries/$id'
    | '/_authenticated/admin/check-po/'
    | '/_authenticated/admin/edit-layout/'
    | '/_authenticated/admin/employees/'
    | '/_authenticated/admin/history/'
    | '/_authenticated/admin/products/'
    | '/_authenticated/admin/roles/'
    | '/_authenticated/admin/salaries/'
    | '/_authenticated/admin/work-schedule-categories/'
    | '/_authenticated/employee/activity-schedule/'
    | '/_authenticated/employee/request-forms/'
    | '/_authenticated/employee/salaries/'
    | '/_authenticated/employee/schedules/'
    | '/_authenticated/admin/employees/edit/$id'
    | '/_authenticated/admin/products/edit/$id'
    | '/_authenticated/admin/products/quantity/add'
    | '/_authenticated/admin/products/quantity/update'
    | '/_authenticated/admin/employees/trash/'
    | '/_authenticated/employee/attendances/calculate/'
    | '/_authenticated/employee/attendances/history/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForbiddenRoute: typeof ForbiddenRoute
}

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForbiddenRoute: ForbiddenRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(auth)",
        "/_authenticated",
        "/forbidden"
      ]
    },
    "/(auth)": {
      "filePath": "(auth)/route.tsx",
      "children": [
        "/(auth)/login"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/activity-schedule",
        "/_authenticated/admin",
        "/_authenticated/employee",
        "/_authenticated/stamps",
        "/_authenticated/work-schedules",
        "/_authenticated/",
        "/_authenticated/request-forms/$id",
        "/_authenticated/scan/storage",
        "/_authenticated/profile/",
        "/_authenticated/request-forms/",
        "/_authenticated/scan/"
      ]
    },
    "/forbidden": {
      "filePath": "forbidden.tsx"
    },
    "/_authenticated/activity-schedule": {
      "filePath": "_authenticated/activity-schedule/route.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/activity-schedule/"
      ]
    },
    "/_authenticated/admin": {
      "filePath": "_authenticated/admin/route.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/admin/products",
        "/_authenticated/admin/salaries",
        "/_authenticated/admin/about",
        "/_authenticated/admin/notification-demo",
        "/_authenticated/admin/attendances/history",
        "/_authenticated/admin/attendances/record",
        "/_authenticated/admin/check-po/add",
        "/_authenticated/admin/check-po/add-export",
        "/_authenticated/admin/check-po/add-inventory",
        "/_authenticated/admin/check-po/history",
        "/_authenticated/admin/employees/add",
        "/_authenticated/admin/plans/material",
        "/_authenticated/admin/plans/production",
        "/_authenticated/admin/check-po/",
        "/_authenticated/admin/edit-layout/",
        "/_authenticated/admin/employees/",
        "/_authenticated/admin/history/",
        "/_authenticated/admin/roles/",
        "/_authenticated/admin/work-schedule-categories/",
        "/_authenticated/admin/employees/edit/$id",
        "/_authenticated/admin/employees/trash/"
      ]
    },
    "/_authenticated/employee": {
      "filePath": "_authenticated/employee/route.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/employee/request-forms",
        "/_authenticated/employee/salaries/$id",
        "/_authenticated/employee/schedules/$id",
        "/_authenticated/employee/stamps/history",
        "/_authenticated/employee/stamps/request",
        "/_authenticated/employee/todo/add-product",
        "/_authenticated/employee/todo/history",
        "/_authenticated/employee/todo/update-quantity",
        "/_authenticated/employee/todo/update-quantity-error",
        "/_authenticated/employee/activity-schedule/",
        "/_authenticated/employee/salaries/",
        "/_authenticated/employee/schedules/",
        "/_authenticated/employee/attendances/calculate/",
        "/_authenticated/employee/attendances/history/"
      ]
    },
    "/_authenticated/stamps": {
      "filePath": "_authenticated/stamps/route.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/stamps/create",
        "/_authenticated/stamps/history"
      ]
    },
    "/_authenticated/work-schedules": {
      "filePath": "_authenticated/work-schedules/route.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/work-schedules/$id",
        "/_authenticated/work-schedules/"
      ]
    },
    "/(auth)/login": {
      "filePath": "(auth)/login.tsx",
      "parent": "/(auth)"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/products": {
      "filePath": "_authenticated/admin/products/route.tsx",
      "parent": "/_authenticated/admin",
      "children": [
        "/_authenticated/admin/products/$id",
        "/_authenticated/admin/products/add",
        "/_authenticated/admin/products/trash",
        "/_authenticated/admin/products/",
        "/_authenticated/admin/products/edit/$id",
        "/_authenticated/admin/products/quantity/add",
        "/_authenticated/admin/products/quantity/update"
      ]
    },
    "/_authenticated/admin/salaries": {
      "filePath": "_authenticated/admin/salaries/route.tsx",
      "parent": "/_authenticated/admin",
      "children": [
        "/_authenticated/admin/salaries/$id",
        "/_authenticated/admin/salaries/"
      ]
    },
    "/_authenticated/employee/request-forms": {
      "filePath": "_authenticated/employee/request-forms/route.tsx",
      "parent": "/_authenticated/employee",
      "children": [
        "/_authenticated/employee/request-forms/authorized",
        "/_authenticated/employee/request-forms/"
      ]
    },
    "/_authenticated/admin/about": {
      "filePath": "_authenticated/admin/about.tsx",
      "parent": "/_authenticated/admin"
    },
    "/_authenticated/admin/notification-demo": {
      "filePath": "_authenticated/admin/notification-demo.tsx",
      "parent": "/_authenticated/admin"
    },
    "/_authenticated/request-forms/$id": {
      "filePath": "_authenticated/request-forms/$id.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/scan/storage": {
      "filePath": "_authenticated/scan/storage.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/stamps/create": {
      "filePath": "_authenticated/stamps/create.tsx",
      "parent": "/_authenticated/stamps"
    },
    "/_authenticated/stamps/history": {
      "filePath": "_authenticated/stamps/history.tsx",
      "parent": "/_authenticated/stamps"
    },
    "/_authenticated/work-schedules/$id": {
      "filePath": "_authenticated/work-schedules/$id.tsx",
      "parent": "/_authenticated/work-schedules"
    },
    "/_authenticated/activity-schedule/": {
      "filePath": "_authenticated/activity-schedule/index.tsx",
      "parent": "/_authenticated/activity-schedule"
    },
    "/_authenticated/profile/": {
      "filePath": "_authenticated/profile/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/request-forms/": {
      "filePath": "_authenticated/request-forms/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/scan/": {
      "filePath": "_authenticated/scan/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/work-schedules/": {
      "filePath": "_authenticated/work-schedules/index.tsx",
      "parent": "/_authenticated/work-schedules"
    },
    "/_authenticated/admin/attendances/history": {
      "filePath": "_authenticated/admin/attendances/history.tsx",
      "parent": "/_authenticated/admin"
    },
    "/_authenticated/admin/attendances/record": {
      "filePath": "_authenticated/admin/attendances/record.tsx",
      "parent": "/_authenticated/admin"
    },
    "/_authenticated/admin/check-po/add": {
      "filePath": "_authenticated/admin/check-po/add.tsx",
      "parent": "/_authenticated/admin"
    },
    "/_authenticated/admin/check-po/add-export": {
      "filePath": "_authenticated/admin/check-po/add-export.tsx",
      "parent": "/_authenticated/admin"
    },
    "/_authenticated/admin/check-po/add-inventory": {
      "filePath": "_authenticated/admin/check-po/add-inventory.tsx",
      "parent": "/_authenticated/admin"
    },
    "/_authenticated/admin/check-po/history": {
      "filePath": "_authenticated/admin/check-po/history.tsx",
      "parent": "/_authenticated/admin"
    },
    "/_authenticated/admin/employees/add": {
      "filePath": "_authenticated/admin/employees/add.tsx",
      "parent": "/_authenticated/admin"
    },
    "/_authenticated/admin/plans/material": {
      "filePath": "_authenticated/admin/plans/material.tsx",
      "parent": "/_authenticated/admin"
    },
    "/_authenticated/admin/plans/production": {
      "filePath": "_authenticated/admin/plans/production.tsx",
      "parent": "/_authenticated/admin"
    },
    "/_authenticated/admin/products/$id": {
      "filePath": "_authenticated/admin/products/$id.tsx",
      "parent": "/_authenticated/admin/products"
    },
    "/_authenticated/admin/products/add": {
      "filePath": "_authenticated/admin/products/add.tsx",
      "parent": "/_authenticated/admin/products"
    },
    "/_authenticated/admin/products/trash": {
      "filePath": "_authenticated/admin/products/trash.tsx",
      "parent": "/_authenticated/admin/products"
    },
    "/_authenticated/employee/request-forms/authorized": {
      "filePath": "_authenticated/employee/request-forms/authorized.tsx",
      "parent": "/_authenticated/employee/request-forms"
    },
    "/_authenticated/employee/salaries/$id": {
      "filePath": "_authenticated/employee/salaries/$id.tsx",
      "parent": "/_authenticated/employee"
    },
    "/_authenticated/employee/schedules/$id": {
      "filePath": "_authenticated/employee/schedules/$id.tsx",
      "parent": "/_authenticated/employee"
    },
    "/_authenticated/employee/stamps/history": {
      "filePath": "_authenticated/employee/stamps/history.tsx",
      "parent": "/_authenticated/employee"
    },
    "/_authenticated/employee/stamps/request": {
      "filePath": "_authenticated/employee/stamps/request.tsx",
      "parent": "/_authenticated/employee"
    },
    "/_authenticated/employee/todo/add-product": {
      "filePath": "_authenticated/employee/todo/add-product.tsx",
      "parent": "/_authenticated/employee"
    },
    "/_authenticated/employee/todo/history": {
      "filePath": "_authenticated/employee/todo/history.tsx",
      "parent": "/_authenticated/employee"
    },
    "/_authenticated/employee/todo/update-quantity": {
      "filePath": "_authenticated/employee/todo/update-quantity.tsx",
      "parent": "/_authenticated/employee"
    },
    "/_authenticated/employee/todo/update-quantity-error": {
      "filePath": "_authenticated/employee/todo/update-quantity-error.tsx",
      "parent": "/_authenticated/employee"
    },
    "/_authenticated/admin/salaries/$id": {
      "filePath": "_authenticated/admin/salaries/$id.lazy.tsx",
      "parent": "/_authenticated/admin/salaries"
    },
    "/_authenticated/admin/check-po/": {
      "filePath": "_authenticated/admin/check-po/index.tsx",
      "parent": "/_authenticated/admin"
    },
    "/_authenticated/admin/edit-layout/": {
      "filePath": "_authenticated/admin/edit-layout/index.tsx",
      "parent": "/_authenticated/admin"
    },
    "/_authenticated/admin/employees/": {
      "filePath": "_authenticated/admin/employees/index.tsx",
      "parent": "/_authenticated/admin"
    },
    "/_authenticated/admin/history/": {
      "filePath": "_authenticated/admin/history/index.tsx",
      "parent": "/_authenticated/admin"
    },
    "/_authenticated/admin/products/": {
      "filePath": "_authenticated/admin/products/index.tsx",
      "parent": "/_authenticated/admin/products"
    },
    "/_authenticated/admin/roles/": {
      "filePath": "_authenticated/admin/roles/index.tsx",
      "parent": "/_authenticated/admin"
    },
    "/_authenticated/admin/salaries/": {
      "filePath": "_authenticated/admin/salaries/index.tsx",
      "parent": "/_authenticated/admin/salaries"
    },
    "/_authenticated/admin/work-schedule-categories/": {
      "filePath": "_authenticated/admin/work-schedule-categories/index.tsx",
      "parent": "/_authenticated/admin"
    },
    "/_authenticated/employee/activity-schedule/": {
      "filePath": "_authenticated/employee/activity-schedule/index.tsx",
      "parent": "/_authenticated/employee"
    },
    "/_authenticated/employee/request-forms/": {
      "filePath": "_authenticated/employee/request-forms/index.tsx",
      "parent": "/_authenticated/employee/request-forms"
    },
    "/_authenticated/employee/salaries/": {
      "filePath": "_authenticated/employee/salaries/index.tsx",
      "parent": "/_authenticated/employee"
    },
    "/_authenticated/employee/schedules/": {
      "filePath": "_authenticated/employee/schedules/index.tsx",
      "parent": "/_authenticated/employee"
    },
    "/_authenticated/admin/employees/edit/$id": {
      "filePath": "_authenticated/admin/employees/edit.$id.tsx",
      "parent": "/_authenticated/admin"
    },
    "/_authenticated/admin/products/edit/$id": {
      "filePath": "_authenticated/admin/products/edit.$id.tsx",
      "parent": "/_authenticated/admin/products"
    },
    "/_authenticated/admin/products/quantity/add": {
      "filePath": "_authenticated/admin/products/quantity/add.tsx",
      "parent": "/_authenticated/admin/products"
    },
    "/_authenticated/admin/products/quantity/update": {
      "filePath": "_authenticated/admin/products/quantity/update.tsx",
      "parent": "/_authenticated/admin/products"
    },
    "/_authenticated/admin/employees/trash/": {
      "filePath": "_authenticated/admin/employees/trash/index.tsx",
      "parent": "/_authenticated/admin"
    },
    "/_authenticated/employee/attendances/calculate/": {
      "filePath": "_authenticated/employee/attendances/calculate/index.tsx",
      "parent": "/_authenticated/employee"
    },
    "/_authenticated/employee/attendances/history/": {
      "filePath": "_authenticated/employee/attendances/history/index.tsx",
      "parent": "/_authenticated/employee"
    }
  }
}
ROUTE_MANIFEST_END */
